### ISSUE TITLE
Link to https://thunderhub.io/ in repo description

### ISSUE THREAD

**Issue by sosojni** [apotdevin/thunderhub#1]
I saw your project on twitter. Liked what i saw. Searched around but Google did not find web site (probably new so it is ignored). Found this repo, but as it has no description or link i was not sure i was looking at the right thing. Having link to web page that has link back to repo makes research for newcomers much faster. I'd create commit but descriptions can't be changed that way.

**Comment by apotdevinc** [comment]
Hey! Sorry for that, will add more info into the repo and also the corresponding two repos for the server and client. Thanks for the suggestion

**Comment by apotdevin** [comment]
Hey, sorry for that, will add more info into this repo and also the 2 corresponding to the server and the client. Thanks for the suggestion!
