### ISSUE TITLE
Select multiple channels to update fees as a group

### ISSUE THREAD

**Issue by Jestopher-BTC** [apotdevin/thunderhub#102]
**Is your feature request related to a problem? Please describe.**
I want to update the fees for only a subset of my channels. Currently, I can either update the fees for all of my channels or I can do them individually. I have a lot of channels for a couple different reasons and each subset requires a different fee policy to be a profitable node. I have to update each channel's fee policy manually and that's a very repetitive process for the user with the way thunderhub currently operates.

**Describe the solution you'd like**
The basic solution for this is to put check boxes next to channels so that the user can select multiple channels and can update the fees and the min HTLC as a group.

**Describe alternatives you've considered**
A more advanced solution would be a to click and drag to select multiple channels with an update fees button. This might go well with a more free-form view of the groups of nodes that you have...general routing, liquidity buys, liquidity sales, friends.

**Provide examples**
If applicable provide examples, wireframes, sketches or images to better explain your idea.
![image](https://user-images.githubusercontent.com/59354805/88491795-ae824280-cf5a-11ea-96d9-3b600bbd9588.png)
 I usually want to update the fees for the loop channels all together since I treat them differently than all my other channels. I would put check boxes to the left of the channel names and have an update fees button/card below the list of channels.

**Comment by apotdevin** [comment]
You can now update multiple channels in batch updates in version 0.9.5 👍
