### ISSUE TITLE
Make port configurable via env var

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#103]
**Is your feature request related to a problem? Please describe.**
I'd love to integrate thunderhub into [my project](github.com/Kixunil/cryptoanarchy-deb-repo-builder/), however port being configured via argument instead of env var makes it problematic because of the inconsistency.

**Describe the solution you'd like**
`BIND_PORT` environment variable to select the port.

**Describe alternatives you've considered**
* Complicate my code a lot by adding support for configuration arguments
* Creating a shell wrapper that reads the config and runs thunderhub with the argument

**Comment by apotdevin** [comment]
Hey! NextJS is a little bit opinionated with this but could you try the solution from this comment? https://github.com/vercel/next.js/pull/11408#issuecomment-617152924

**Comment by Kixunil** [comment]
Ah, didn't know it's a limitation of external tool. Sure I'm using pretty much the same thing for now. I'm going to close this at least until `next` has the required feature..
