### ISSUE TITLE
I'm unable to login using SSO (perhaps unclear documentation?)

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#108]
**Describe the problem/bug**
When attempting to log in using `?token=...` I get this message:

> To start you must create an account on your server. You can find instructions for this here.

I did not setup yaml file with accounts because my understanding of the documentation is that those accounts are independent from SSO account (they don't use cookie but passwords). Even if I understand it incorrectly, I'm not sure what would be the proper way to configure SSO. Would I just duplicate the information from env vars to yaml? Can I omit the password?

**Your environment**
* Version of ThunderHub: 0.8.13
* Deployment method: Debian package
* Other relevant environment details: not sure if relevant, but I access it over Tor

<details>
<summary>Environment configuration</summary>

```
BIND_PORT=4002

BITCOIN_NETWORK=regtest

COOKIE_PATH=/var/run/thunderhub-system-regtest/sso/cookie

DISABLE_LINKS=true

FETCH_FEES=false

FETCH_PRICES=false

HODL_HODL=false

NO_CLIENT_ACCOUNTS=true

NO_VERSION_CHECK=true

SSO_CERT_PATH=/var/lib/lnd-system-regtest/public/tls.cert

SSO_MACAROON_PATH=/var/lib/lnd-system-regtest/private/admin.macaroon

SSO_SERVER_URL=127.0.0.1:10011

BASE_PATH=/thunderhub-rt
```

</details>

**To Reproduce**
1. Setup SSO using above mentioned configuration
2. Generate the cookie using `head -c 18 /dev/urandom | base64 > $cookie_file`
3. Launch ThunderHub
4. Open the browser with ThunderHub URL and `?token=...`
5. See the message
6. Try to change the token to something invalid
7. See the same message (is token ignored?)

**Expected behavior**
The SSO account shows up and I'm able to access it.
When an invalid token is entered I get "Invalid authentication token" message (step 7).

**Actual behavior**
"To start you must create an account on your server. You can find instructions for this here." message

**Comment by apotdevin** [comment]
When you go to `.../?token=...` does the browser redirect you to `.../` ?

Any logs?

And you have filled all these envs?: https://github.com/apotdevin/thunderhub#sso-account

**Comment by Kixunil** [comment]
So I got it working, but please continue reading.

No redirect., with `LOG_LEVEL=silly`:

```
Jul 30 12:19:21 disp6180 systemd[1]: Started Lightning Node Manager.
Jul 30 12:19:22 disp6180 thunderhub[5673]: ready - started server on http://localhost:4002
Jul 30 12:21:48 disp6180 thunderhub[5673]: 2020-07-30 12:21:48 error [THUB]: No admin.macaroon file found at path: /var/lib/lnd-system-regtest/private/admin.macaroon/admin.macaroon
Jul 30 12:21:48 disp6180 thunderhub[5673]: 2020-07-30 12:21:48 verbose [THUB]: No account config file path provided
Jul 30 12:21:48 disp6180 thunderhub[5673]: 2020-07-30 12:21:48 verbose [THUB]: Found cookie at path /var/run/thunderhub-system-regtest/sso/cookie
Jul 30 12:21:48 disp6180 thunderhub[5673]: 2020-07-30 12:21:48 warn [THUB]: Host and macaroon are required for SSO
```

Strangely I didn't see those logs before setting `LOG_LEVEL` not sure if it's a bug or I made some mistake.

It looks like ThunderHub is appending `admin.macaroon` to the `MACAROON_PATH`, which is surprising. I'd recommend not doing it. In case you insist on appending, the variable should be called `MACAROON_DIR` to not confuse the users.

After removing `admin.macaroon` from my configuration (so that the resulting path contains it only once), it works!

**Comment by apotdevin** [comment]
Glad it works, will take it into account! Thanks for the suggestion :)

**Comment by Kixunil** [comment]
Man, I finally tried it out on a live instance. I must say this is the single best LN management tool I've seen so far!!! It looks awesome, has tons of features and it was much easier to integrate into my repository than some other software. I've sent you some sats and I will make sure to promote this tool to everyone. I'm very happy having it in my repo.

Once the repo has a proper logo and ceases to be experimental (shouldn't be too long away) I'll ping you about adding it to the official list of integrations.

Thanks again for a great product!

**Comment by apotdevin** [comment]
Very appreciated! Glad you like it and that it was simple to integrate!

Just let me know and i'll add it in 👍

PS: Mind if I share part of your comment on twitter?

**Comment by Kixunil** [comment]
No problem! I will be happy to retweet it later (I'm staying off of Twitter for a while).

**Comment by Kixunil** [comment]
Forgot to add: your quick and helpful replies were also great, thanks a lot!
