### ISSUE TITLE
Tags not signed

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#114]
**Describe the problem/bug**
Signing tags is a very important safety measure to prevent attacks against bitcoiners running thunderhub and thus stealing from LN nodes. The tags are not signed.

Further, the GPG fingerprint used for signing should be published at various independent websites (ideally using keybase) and the key should be available at public key servers (e.g. hkp://keyserver.ubuntu.com)

**To Reproduce**
1. `git clone https://github.com/apotdevin/thunderhub/
2. `cd thunderhub`
3. `git verify-tag v0.8.13`

**Expected behavior**
`git` produces error message about missing key

**Actual behavior**
The error message says (in a very convoluted way) that the tag is not signed.

**Comment by apotdevin** [comment]
Done! Latest tag should be verified :)

`git verify-tag v0.8.14`

**Comment by Kixunil** [comment]
OMG, my new build finished literally minutes ago, so I have to rebuild again. :D Thanks a lot!
