### ISSUE TITLE
Missing @types/styled-components

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#117]
**Describe the problem/bug**
When trying to build ThunderHub 0.9 the build fails with this error:

```
Type error: Could not find a declaration file for module 'styled-components'. '/home/user/cadr-build/thunderhub-0.9.0/node_modules/styled-components/dist/styled-components.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/styled-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'styled-components';`
```

Running `npm install @types/styled-components` seems to help but I suspect it's not deterministic, so it'd be nicer to have the dependency committed.

**Your environment**
* Version of ThunderHub: 0.9
* Deployment method: Debian package
* Other relevant environment details: Debian 10, nodejs 10.21.0, npm 5.8.0

**To Reproduce**
1. `git clone -b v0.9.0 ...`
2. `cd thunderhub`
3. `npm install --production`

**Expected behavior**
Build succeeds

**Actual behavior**
Build fails with the message above

**Comment by Kixunil** [comment]
Strangely, I'm now unable to build it at all (tried second time to see if the build is deterministic)

**Comment by apotdevin** [comment]
That's strange... the types are there but as dev dependencies and next had never failed to build..

Seems like they changed something in the latest nextjs version, I'll have a look. Thanks for catching this!

**Comment by apotdevin** [comment]
Ok, had a look and seems like now the nextjs build is expecting most dependencies for the build but non production dependencies can later be removed.

I changed the dockerfiles as well to go with this. It's following these steps now:
```
npm install
npm run build
npm prune --production
```

Let me know if something like this works for you?

**Comment by Kixunil** [comment]
Yes, it works, thanks!
