### ISSUE TITLE
0.9.0: BASE_PATH seems to be ignored

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#118]
**Describe the problem/bug**
When I attempt to use ThunderHub with `BASE_PATH=thunderhub-rt` it appears to ignore `BASE_PATH`. I get error 404 and if I try to remove rewrite from nginx I get redirected to `/home` after selecting the SSO account.

**Your environment**
* Version of ThunderHub: 0.9.0
* Deployment method: Debian package
* Other relevant environment details: chromium 83.0.4103.116  with webdriver (attempting to write selenium test)

**To Reproduce**
1. Configure `BASE_PATH=thunderhub-rt`
2. Configure rewrite in nginx
3. Open `yourdomain.tld/thunderhub-rt?token=...`
4. See error 404

**Expected behavior**
A page with SSO button.

**Actual behavior**
Error 404

**Additional context**

<details>
<summary>Configuration</summary>

```
BIND_PORT=4002

BITCOIN_NETWORK=regtest

COOKIE_PATH=/var/run/thunderhub-system-regtest/sso/cookie

DISABLE_LINKS=true

FETCH_FEES=false

FETCH_PRICES=false

HODL_HODL=false

NO_CLIENT_ACCOUNTS=true

NO_VERSION_CHECK=true

SSO_CERT_PATH=/var/lib/lnd-system-regtest/public/tls.cert

SSO_MACAROON_PATH=/var/lib/lnd-system-regtest/private

SSO_SERVER_URL=127.0.0.1:10011

BASE_PATH=/thunderhub-rt
```

</details>

<details>
<summary>Log</summary>

```
Aug 09 08:18:49 disp6996 systemd[1]: Starting Lightning Node Manager...
Aug 09 08:18:49 disp6996 systemd[1]: Started Lightning Node Manager.
Aug 09 08:18:50 disp6996 thunderhub[7017]: ready - started server on http://localhost:4002
```

</details>

<details>
<summary>Nginx config</summary>

```
location /thunderhub-rt {
	rewrite ^/thunderhub-rt$ / break;
        rewrite ^/thunderhub-rt(.*)$ $1 break;
	proxy_pass http://127.0.0.1:4002;
	proxy_http_version 1.1;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
}
```

</details>

**Comment by apotdevin** [comment]
Ah another change that came from the latest Nextjs version which is maybe not working as expected...

I'll have a look!

**Comment by apotdevin** [comment]
So the `base path` changes in the latest nextjs release weren't working as expected so reverted some changes to how they where before.

If you can try version 0.9.1, it should be working again

**Comment by Kixunil** [comment]
Updated straight to 0.9.2 and it runs now, thanks!
