### ISSUE TITLE
Redirect to login instead of 500 error

### ISSUE THREAD

**Issue by shawnyeager** [apotdevin/thunderhub#129]
**Is your feature request related to a problem? Please describe.**
Currently, with v9.0.4, visiting a bookmark of `/home` after timeout results in an internal server error (500). 

**Describe the solution you'd like**
Redirect back to login.

**Additional context**
![image](https://user-images.githubusercontent.com/980297/90586634-457a9d00-e19d-11ea-942e-c137c11f2fb5.jpeg)

**Comment by apotdevin** [comment]
Ah yes, a side effect from the SSR rendering. Need to improve this, thanks!

**Comment by apotdevin** [comment]
Fixed on version 0.9.7 (adc935269ccad538957dba30d4cca4f26d73dff0)

**Comment by shawnyeager** [comment]
Hey, @apotdevin, FYI that I'm still experiencing this with TH v0.9.7 under raspiblitz v1.6.

**Comment by apotdevin** [comment]
Any logs that appear on the server? So just be visiting '/home' you get this error?

If you go to '/' and login and then refresh on '/home' does it still happen?

**Comment by shawnyeager** [comment]
I have /home bookmarked. I'm not clear on login timeout, but when my login has timed out and I attempt to access the bookmark, I'll see the 500 error. After I login, all is well.

What logs would be useful?

**Comment by apotdevin** [comment]
hmm can't reproduce this locally. And you are on the latest version?

Any logs that appear on the server when going to `/home`?

**Comment by apotdevin** [comment]
Login flow has been refactored since some versions ago and should behave better. Closing this but feel free to reopen if theres still some issue!
