### ISSUE TITLE
option to proxy external calls over Tor or VPN

### ISSUE THREAD

**Issue by openoms** [apotdevin/thunderhub#130]
**Is your feature request related to a problem? Please describe.**
Exposing Public IP of the node when calling external services 

**Describe the solution you'd like**
Have an option available in the config file or in the systemd service to proxy all communication through Tor or a VPN

**Describe alternatives you've considered**
Proxying all communication on a system level

**Provide examples**
Running loopd with 
` --server.proxy=127.0.0.1:9050`

**Comment by apotdevin** [comment]
Interesting, will look into it!

**Comment by apotdevin** [comment]
Duplicate, closing in favor of https://github.com/apotdevin/thunderhub/issues/175
