### ISSUE TITLE
QoL Feature: Enter Key to use Login Form

### ISSUE THREAD

**Issue by Amperture** [apotdevin/thunderhub#131]
**Is your feature request related to a problem? Please describe.**
Quality of Life improvement. On the login form, I'm very used to web forms reacting to the enter key as if it were clicking the submit/connect button, but the login page in ThunderHub does not.

**Describe the solution you'd like**
After inputting my password on the Login page, I should be able to press enter to log in, instead of needing to click the "Connect" button.

**Additional context**
Possibly use the onKeyPress event detector in React? https://www.pluralsight.com/guides/how-to-enter-key-event-handler-on-a-react-bootstrap-input-component

Not familiar with React+TS, so not 100% sure the link supplied is suitable. May test on personal fork later.

**Comment by apotdevin** [comment]
Yes! I must get to this 👍 Thanks for opening the request

**Comment by apotdevin** [comment]
Fixed with 5988231bcf526499af731cae461499f89eeb56a3
