### ISSUE TITLE
Stats give 500 internal server error

### ISSUE THREAD

**Issue by bloodir** [apotdevin/thunderhub#132]
**Describe the problem/bug**
When I click on in Thunderhub STATS, I receive 500 internal error.

**Your environment**
* Version of ThunderHub: 0.9.0
* Deployment method: mynode /raspi4
* Other relevant environment details:

**Screenshots/Links**
![thub](https://user-images.githubusercontent.com/44784060/90989735-34dc8380-e5f0-11ea-9c24-095717ef28b1.png)

This issue was not happening when I had no channels open earlier yday, later I opened channels and this started to happen.

**Comment by apotdevin** [comment]
Thanks for opening the issue! Will look into it

**Comment by bloodir** [comment]
Just upgraded to 0.9.8 and same error is still happening.

**Comment by apotdevin** [comment]
Already fixed
