### ISSUE TITLE
Add ability to stipulate an expiration time/date when creating a Lightning invoice.

### ISSUE THREAD

**Issue by davterra** [apotdevin/thunderhub#134]
New user, and I can quickly see ThunderHub becoming my main-use wallet.
However, unless I'm missing something in the GUI, it seems that there is no ability to add an expiration
time or date to a Lightning invoice.

If I'm wrong, please correct me.

Thank you!

**Comment by apotdevin** [comment]
Need to add this! Glad you've liked it and thanks for opening the feature request 🏅

**Comment by apotdevin** [comment]
You can now add seconds until expiration when creating an invoice with commit e0e6c3b45d3f89094625d8c6e8e2a5cb0d455e5a
