### ISSUE TITLE
Advance Rebalance type "auto" missing explanation and always fails

### ISSUE THREAD

**Issue by sendbitcoin** [apotdevin/thunderhub#146]
![2020-09-24 17_21_20-ThunderHub - Lightning Node Manager](https://user-images.githubusercontent.com/60074674/94165332-631cdf80-fe8a-11ea-9208-aacc7eef975a.png)

No idea what exactly this "auto" rebalance is supposed to do exactly. needs more tooltips, explanations and settings.

pressing the button anyway results in error:

![2020-09-24 17_22_31-ThunderHub - Lightning Node Manager](https://user-images.githubusercontent.com/60074674/94165486-91022400-fe8a-11ea-851f-80018b0ca1d6.png)

I have plenty of inbound channels with capacity so that error is bullshit. maybe tell me more information regarding what happened (amount routed, path, peer, error) cause that error doesnt tell me what went wrong at all.

version 0.9.8

**Comment by apotdevin** [comment]
Yeah, this definitely needs to be explained more. Will see what I can do.

In the mean time can you try selecting the channels that you want to rebalance manually by going into the `Detailed` mode? The auto mode sometimes fails to find goods channels and gives this error

**Comment by DocBrown101** [comment]
Your "rebalance" approach is very good and could become a unique selling point if it works well in the future!

**Comment by apotdevin** [comment]
This view has been refactored on version 0.12.6 and should be more straightforward to follow. Closing but feel free to open if there are still any concerns
