### ISSUE TITLE
Advanced rebalance type "detailed" is very unclear and needs tooltips

### ISSUE THREAD

**Issue by sendbitcoin** [apotdevin/thunderhub#147]
![2020-09-24 17_26_56-ThunderHub - Lightning Node Manager](https://user-images.githubusercontent.com/60074674/94166084-33baa280-fe8b-11ea-9f14-89873fcaa552.png)

What does "with node" mean? is that the node taking local balance from? needs better wording and a mouseover tooltip explaining it.

What does "avoid node" do exactly? does it completely exclude all routes that contain that node? what if those are the only ones available? wording unclear, should probably be exclude instead of avoid and needs a tooltip to explain what it does.

What does "avoid high inbound" do? no idea... needs explanation tooltip or better wording

Are max fee and max feerate mandatory field?

Max feerate is hard to understand as ppm and should be in % for a better UX. or at least add tooltip explaining how you get from ppm to % cause currently i have no idea how much ppm 10000 or 1000 is converted into % without pulling up a calulator and looking up how feerate works

what does "max rebalance" do? is this the biggest size of payment that will be made to rebalance? is this the total max amount that will be rebalanced? no idea... needs explanation or better wording.

what does "target amount" do exactly? what the difference to "max rebalance"

I could probably figure some of these out by trial and error if it would work but it always fails with this error so I can't figure out if i'm doing something wrong or if it's just broken:

![2020-09-24 17_22_31-ThunderHub - Lightning Node Manager](https://user-images.githubusercontent.com/60074674/94173779-b09e4a00-fe94-11ea-85f0-e33e20a48a1a.png)

In general i'm just very confused what this page is supposed to do. Is it just gonna do a single rebalance? or is it gonna make many payments to achieve the desired result? a general explanation text of the page should probably be included at the top of the page.

version 0.9.8

**Comment by apotdevin** [comment]
Totally agree, need to get more information into this section explaining the purpose of each of these options 👍

**Comment by apotdevin** [comment]
This view has been refactored on version 0.12.6 and should be more straightforward to follow. Closing but feel free to open if there are still any concerns
