### ISSUE TITLE
How to create LN-withdraw links

### ISSUE THREAD

**Issue by daldwinc** [apotdevin/thunderhub#149]
Hi,

I'm running 0.9.14 and trying to figure out how to create a new LN-withdraw link. 

I was happy to see the new quick link here:

![image](https://user-images.githubusercontent.com/36732642/94437174-63a7c580-016b-11eb-861d-50c35ff6a16b.png)

Clicking the button changes the screen to this:

![image](https://user-images.githubusercontent.com/36732642/94437280-86d27500-016b-11eb-9dcc-6e2589162437.png)

Based on the README noting "LNURL integration: ln-pay and ln-withdraw are available. Ln-auth soon" - I was expecting to be able to create a new LN-withdraw link that I could share with others. 

Am I looking in the wrong place?
Could this be a new feature request? 

If its relevant, I have my Thunderhub installation running on an internet routable IPv4 address, and lightning running as a Tor hidden service.

**Comment by apotdevin** [comment]
Hey! So Lnurl defines the conversation between 2 parties. In the case of ln-withdraw the conversation goes along the lines of:

1. PERSON tells the SERVER that he would like to withdraw
2. SERVER responds to the PERSON how much he can withdraw
3. PERSON gives the SERVER an invoice to pay
4. SERVER pays the invoice and PERSON has successfully withdrawn.

As you see, there are 2 sides to this conversation. The person and the server. For all the lnurl implementations on ThunderHub you are the person, so for ln-withdraw you actually need to provide the LNURL that a server has given to you.

If you want to test it out you can try this website: https://lnurl.bigsun.xyz/

**Comment by daldwinc** [comment]
Hi @apotdevin 

Thanks for the explanation!

I'll look into finding another tool to act as the server.
