### ISSUE TITLE
red channel dots at rebalance screen

### ISSUE THREAD

**Issue by Marcoblue** [apotdevin/thunderhub#150]
On the Rebalance screen, in simple view, each channel has a red dot on the right side. I suspect that this is meant to represent some kind of rebalance score. But also the well balanced channels are red.
![rebalance](https://user-images.githubusercontent.com/71592699/94442666-83a7ab00-01a4-11eb-9610-81187532a25d.jpg)

**Comment by apotdevin** [comment]
Hey! Which version are you one? This has been fixed in later versions already

**Comment by Marcoblue** [comment]
Oh, sorry I have 0.8.12 that still comes with Raspiblitz. A Issue is open there.

**Comment by apotdevin** [comment]
No problem, you should be able to update from the update option on the raspiblitz main screen 👍
