### ISSUE TITLE
Docker arm64 not working (image not published)

### ISSUE THREAD

**Issue by NicolasDorier** [apotdevin/thunderhub#151]
apotdevin/thunderhub:v0.9.8
```
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

it worked in v0.9.3

**Comment by apotdevin** [comment]
Aha strange, let me trigger the build for that version again

**Comment by apotdevin** [comment]
Ok build is running and it should be available soon. Also bumped the version in btcpay to the latest: https://github.com/btcpayserver/btcpayserver-docker/pull/374

**Comment by apotdevin** [comment]
Images are all pushed for version v0.9.8, thanks for the headsup!
