### ISSUE TITLE
Unable to connect to this node

### ISSUE THREAD

**Issue by Janaka-Steph** [apotdevin/thunderhub#154]
**Describe the problem/bug**
Trying to connect via SSO returns the UI error "Unable to connect to this node".

**Your environment**
* Version of ThunderHub: apotdevin/thunderhub:v0.9.15
* Deployment method: BTCPay v1.0.5.6 on Odroid XU4
* Other relevant environment details:
I followed the tutorial https://apotdevin.com/blog/thunderhub-btcpay.
Since I already have a node I only did:
```
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-thunderhub"
. btcpay-setup.sh -i
```

Docker ThunderHub logs:
```
root@btcpayServer:~/BTCPayServer# docker logs 5520fb222fc6

> thunderhub@0.9.14 start:cookie /app
> sh ./scripts/initCookie.sh "/data/.cookie"

Creating cookie file for SSO authentication at /data/.cookie
Cookie file created.
Starting ThunderHub server...

> thunderhub@0.9.14 start /app
> next start

ready - started server on http://localhost:3000
2020-10-10 13:22:40 verbose [THUB]: Found cookie at path /data/.cookie
2020-10-10 13:22:40 verbose [THUB]: No account config file path provided
2020-10-10 13:22:41 warn [THUB]: No SSO account available
2020-10-10 13:22:41 verbose [THUB]: Found cookie at path /data/.cookie
2020-10-10 13:22:41 verbose [THUB]: Refreshing cookie for next authentication
2020-10-10 13:22:43 debug [THUB]: Macaroon, certificate and host (lnd_bitcoin:10009) found for SSO.
2020-10-10 13:22:49 error [THUB]: [ 503, 'FailedToConnectToDaemon', [length]: 2 ]
```

Am I suppose to add a config file or do something else? 

Thank you

**Comment by apotdevin** [comment]
Hi! [Check this tutorial on the setup](https://apotdevin.com/blog/thunderhub-btcpay). At the very bottom there is a `There's an Error!` section that will most likely solve your problem :)

**Comment by Janaka-Steph** [comment]
Indeed, that was it! Sorry I missed that section. 
Well now I have an other issue which is that I logged out and can't log back in. Homepage says "To start you must create an account on your server. You can find instructions for this here."
The only logs I have are:
```
2020-10-11 12:23:48 verbose [THUB]: Found cookie at path /data/.cookie
2020-10-11 12:23:48 verbose [THUB]: No account config file path provided
``` 
I can close this issue and open an other one if you prefer.

**Comment by apotdevin** [comment]
To be able to login with your BTCPayServer authentication you always need to access ThunderHub from the link inside BTCPay which should be something like `[yourBTCPayUrl]/server/services/thunderhub/BTC`

**Comment by Janaka-Steph** [comment]
Oh I see, you are passing a token.. Thank you for your help and for this great app!
