### ISSUE TITLE
Can't set fees on force close channel

### ISSUE THREAD

**Issue by bota87** [apotdevin/thunderhub#155]
If I try to set the fees and force close channel an error pop-up "UnexpectedFeeSettingForForceCloseChannel"

**Comment by apotdevin** [comment]
Hey! In part this is a correct behaviour, you cannot set the fees when it's a force close but ThunderHub should also hide the manual fee input bar when you set `Force Close` to avoid confusion.

**Comment by apotdevin** [comment]
Closed with ed583441d3f96672c7909c71c754e9e3052ec225
