### ISSUE TITLE
Was the signing key changed or am I being attacked?

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#156]
**Describe the problem/bug**
I'm attempting to verify the newest release of ThunderHub with key `3C8A01A8344B66E7875CE5534403F1DFBE779457`. This same key is present on keybase.
However, `git verify-commit` is attempting to use `4AEE18F83AFDEB23` which is not known.

**Your environment**
* Version of ThunderHub: 0.9.15
* Deployment method: Irrelevant
* Other relevant environment details: source pulled by `git clone`

**To Reproduce**
1. `git clone -b v0.9.15 https://github.com/apotdevin/thunderhub`
2. `gpg --recv-keys 3C8A01A8344B66E7875CE5534403F1DFBE779457`
3. `cd thunderhub`
4. `git verify-tag`

**Expected behavior**
Commit has a valid signature

**Actual behavior**
```
gpg: Signature made Fri 25 Sep 2020 06:50:39 PM CEST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
```

**Comment by apotdevin** [comment]
Hey! Sorry for that. That commit was actually signed by [Github](https://security.stackexchange.com/questions/173493/who-owns-the-gpg-key-4aee18f83afdeb23-and-how-did-it-sign-a-commit-in-my-github) and not my key.

I believe I did a merge directly from Github which triggered this signing. Github signs under the following conditions:

- GitHub will sign commits made using the web UI
- GitHub will sign standard merges made using the web UI
- GitHub will sign commits made by squashing to merge using the web UI

Will keep it in mind from now on

**Comment by Kixunil** [comment]
Would you mind making a dummy point release (nothing changed, just version number and a dummy commit added)? Would prefer not to trust GitHub too much.

**Comment by apotdevin** [comment]
For sure 👍

**Comment by Kixunil** [comment]
It works now, thanks!
