### ISSUE TITLE
change base fee to 0 sat not possible

### ISSUE THREAD

**Issue by Marcoblue** [apotdevin/thunderhub#157]
**Describe the problem/bug**
It is not possible to set a base fee of 0. It must be at least 1. With RTL 0sat is possible.

**Your environment**
* Version of ThunderHub: 0.9.16
* Deployment method: 
* Other relevant environment details:

**To Reproduce**
1. Go to 'Channels'
2. Click on 'Fees; Update Details'
3. See error: It dont changes

**Expected behavior**
Change base fee to 0 sat.

**Actual behavior**
Still 1 sat base fee.

**Comment by apotdevin** [comment]
Thanks for opening the request!

**Comment by cryptoteun** [comment]
By typing .1 it is possible to set it to 0.1 instead of 1, but would be great if it's possible to set it to 0.

**Comment by apotdevin** [comment]
Closed by https://github.com/apotdevin/thunderhub/issues/183
