### ISSUE TITLE
GUI: "Unable to connect to node"

### ISSUE THREAD

**Issue by daldwinc** [apotdevin/thunderhub#161]
**Describe the problem/bug**

Since updating to 0.10.0, when navigating around the GUI I will get a notification that says "Unable to connect to node", and I'm kicked out to the login page. I can login again and work for a few seconds, a minute in some cases, and then get kicked out again. I can see that the GUI is correctly reporting the details of my peers and channels, so it is able to reach the node.

**Your environment**
* Version of ThunderHub: 0.10.0
* Deployment method: RaspiBlitz v1.6.0 - using the RaspiBlitz update option for Thunderhub
* Other relevant environment details: LND 0.11.1-beta

**To Reproduce**
1. Navigate to GUI and login
2. Click around to a few screens or simply just wait on the home page
3. Notification should appear in the top right 

**Expected behavior**
This did not occur on previous versions of Thunderhub.

**Actual behavior**
As I was writing this report, I tried to quickly open a channel, and I was able to do so. I clicked the channels tab and got a 500 error. I refreshed the page and my channels screen loaded. A few seconds later I got the "Unable to connect to node" popup and was logged out.

**Comment by apotdevin** [comment]
Hey! Thanks for opening the ticket. Which version of NodeJs is running on the raspiblitz? You can check by running `node --version` by command line

**Comment by apotdevin** [comment]
Just checked with a nodeJs version 10 and get the same error. Try upgrading NodeJS on the raspiblitz this should work

**Comment by apotdevin** [comment]
Here's the script for updating nodejs on the raspiblitz :) https://github.com/rootzoll/raspiblitz/pull/1748#issue-517123777

**Comment by daldwinc** [comment]
I used the script in the linked thread which installed node v14.5.0 for me.  Then a reboot of the pi and I'm back in business.

Thanks!

**Comment by apotdevin** [comment]
no problem!
