### ISSUE TITLE
Mitigate brute force attacks with fail2ban

### ISSUE THREAD

**Issue by bota87** [apotdevin/thunderhub#164]
I found that thunderhub authentication is vulnerable to brute force attacks so I tried to mitigate this by using fail2ban but actualy this is not possible because the failed attempt is not logged.
If you add a message in the log every time a login is failed than I can create a filter for fail2ban and ban the request host after X failed attempt.
It's important that in the message is present the ip address of the request host, it could be something like:
`Authentication failed from [<host ip address>]: Invalid Password!`

**Comment by apotdevin** [comment]
Oh, there should be a rate limiter in place that only allows 5 calls per 5 seconds per ip. I could also decrease this value if you think it would help?

I'll also add a log in this same format 👍  Thanks for the request!

**Comment by apotdevin** [comment]
Added the log in version 0.10.3

**Comment by bota87** [comment]
You did it super fast! Here is the filter and the jail if someone need it

```
# /etc/fail2ban/filter.d/thunderhub-auth.conf
[Definition]

failregex = ^.+ \[THUB\]: Authentication failed from ip: <HOST> - Invalid Password!$

ignoreregex =
```

```
# /etc/fail2ban/jail.local
...
[thunderhub-auth]
enabled  = true
port     = <thunderhub port here>
logpath  = %(syslog_daemon)s
...
```
