### ISSUE TITLE
error [THUB]: Account in index 0 is missing the fields server url, macaroon

### ISSUE THREAD

**Issue by Prabhudevaraju** [apotdevin/thunderhub#167]
**Describe the problem/bug**

Error while starting npm.

~/thunderhub $ npm start

> thunderhub@0.10.4 start /home/bitcoin/thunderhub
> next start

Loaded env from /home/bitcoin/thunderhub/.env
ready - started server on http://localhost:3000
2020-11-21 15:55:46 error [THUB]: Account in index 0 is missing the fields server url, macaroon
2020-11-21 15:55:46 info [THUB]: Server accounts that will be available:

**Your environment**
* Version of ThunderHub: 0.10.4
* Deployment method:  Manual
* Other relevant environment details:

**.env file**

# -----------
# IMPORTANT
# Create a new file called .env.local and copy
# the environment variables that you want to
# change to this file. This way they won't be
# overwritten when you update thunderhub.
# -----------

# -----------
# Server Configs
# -----------
# LOG_LEVEL='info'
# BASE_PATH='/basePath'

# -----------
# Interface Configs
# -----------
 THEME='dark'
 CURRENCY='sat'

# -----------
# Privacy Configs
# -----------
FETCH_PRICES=true
FETCH_FEES=true
DISABLE_LINKS=false
DISABLE_LNMARKETS=false
NO_VERSION_CHECK=false

# -----------
# Account Configs
# -----------
ACCOUNT_CONFIG_PATH='/home/bitcoin/thunderhub/thubConfig.yaml'

# -----------
# SSO Account Configs
# -----------
# COOKIE_PATH='/path/to/cookie/.cookie'
# SSO_SERVER_URL='127.0.0.1:10009'
# SSO_CERT_PATH='/path/to/certificate/tls.cert'
#SSO_MACAROON_PATH='/path/to/folder/containing/macaroons'

**thubConfig.yaml**

masterPassword: 'PASSWORD'
accounts:
  - name: 'TBM'
serverUrl: '127.0.0.1:10009'
macaroonPath: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
certificatePath: '/home/bitcoin/.lnd/tls.cert'
password: 'accountpassword'

**To Reproduce**
1. npm start
2. Error
 error [THUB]: Account in index 0 is missing the fields server url, macaroon

**Comment by apotdevin** [comment]
It seems it cant read the yaml file. Can you paste here the yaml contents in the same formatting you have it in the file?

**Comment by Prabhudevaraju** [comment]
masterPassword: thunderhub-$2a$12$.c7.2WzgwRj30za32oftOJCXVIfkEcFOqyXJoMcwsoLM6d$
accounts:
  _-_ name: 'thebitcoinmachine'
serverUrl: '127.0.0.1:10009'
macaroonPath: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
certificatePath: '/home/bitcoin/.lnd/tls.cert'
password: 'TheBitcoinMachine'

**Comment by Prabhudevaraju** [comment]
Removed account password line, now it works. Thanks.


masterPassword: 'PASSWORD'
accounts:
  - name: 'thebitcoinmachine'
    serverUrl: '127.0.0.1:10009' # or whichever port where you are running the gRPC endpoint
    macaroonPath: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
    certificatePath: '/home/bitcoin/.lnd/tls.cert'
