### ISSUE TITLE
Can't enter a custom lnurl-pay amount

### ISSUE THREAD

**Issue by moonshot75** [apotdevin/thunderhub#168]
**Describe the problem/bug**
When trying to adjust the amount of sats for a lnurl-pay I can only use +/- and enter numbers after the default minimum.
It's not possible to change 100 into for example 200 by typing.

**Your environment**
ThunderHub 0.10.1

**To Reproduce**
1. Click LNURL on /home
2. Enter lnurl-pay example: lnurl1dp68gurn8ghj7ctsdyh85etzv4jx2efwd9hj7a3s9aex2ut4v4ehgttnw3shg6tr943ksctjvajhxtm9xqcnwdf3xy6j6vp4xc6z6dryvvmj6wfjvdjz6dn9xq6rgcmxv93k2wtpwm4jhu and Confirm
3. Click on Amount input field
4. Try to set another amount

**Expected behavior**
Number changes

**Actual behavior**
Changing fails

**Screenshots/Links**
![screenshot (2)](https://user-images.githubusercontent.com/66482965/99888293-02244480-2c4c-11eb-9272-d2531fdebee2.png)

**Comment by apotdevin** [comment]
Thanks for finding the bug! Should be fixed in version 0.10.5
