### ISSUE TITLE
Forwards report truncates most recent transactions if more than ~100?

### ISSUE THREAD

**Issue by wroscoe** [apotdevin/thunderhub#171]
**Describe the problem/bug**
I have forwarded over 101 transactions for the week. On the forwards page I can only see the oldest 100 (could be less) transactions. If I go to the day range, I can see the recent transactions that occurred today.

**Your environment**
* Version of ThunderHub: 0.9.14
* Deployment method: 
* Other relevant environment details:

**To Reproduce**
1. Go to Forwards tab
2. Click to show week date range for the list of forwards.
3. Click to show day date range for the list of forwards.

**Expected behavior**
I'd expect to always see the most recent transactions even if there are more than 100.

**Actual behavior**
The oldest 100 transactions are shown.

**Comment by apotdevin** [comment]
Could you update to the latest release and see if this is still present? I refactored a lot of the code for the forwards view and this might be fixed already :)

**Comment by wroscoe** [comment]
yep, updated to 0.10.1 and its fixed. Thanks!
