### ISSUE TITLE
Thunderhub causes LND to run out of file descriptors

### ISSUE THREAD

**Issue by accumulator** [apotdevin/thunderhub#172]
**Describe the problem/bug**
Keeping open thunderhub in the browser steadily increases the amount of used file descriptors by LND, probably because new connections to LND are made for every request and old ones are kept open.

**Your environment**
* Version of ThunderHub: v0.10.4-amd64
* Deployment method: Docker
* Other relevant environment details:

**To Reproduce**
1. Run the thunderhub container
2. Browse to thunderhub
3. log in and leave the page open
4. Observe file descriptors increasing, e.g. by `watch ls /proc/<lnd pid>/fd/|wc -l`

After some time, LND gets into trouble (max open files limit=1024)

```
nov 23 12:57:44 host lnd[1689]: 2020-11-23 12:57:43.930 [ERR] BTCN: Can't
accept connection: accept tcp [::]:9735: accept4: too many open files
...snip...
nov 23 12:57:44 host lnd[1689]: 2020-11-23 12:57:43.931 [ERR] BTCN: Can't
accept connection: accept tcp [::]:9735: accept4: too many open files
nov 23 12:58:14 host systemd-journald[289]: Suppressed 93628 messages from
lnd.service
```

Logging out or closing the thunderhub browser tab stops the increase in file descriptors.
Stopping the container reduces the file descriptors to normal values.

**Comment by apotdevin** [comment]
Interesting, had never checked this out. Need to look more into it.

Thanks for the reporting this!

**Comment by Roasbeef** [comment]
Assuming Thunderhub uses streaming RPCs heavily, it could be possible that the stream themselves aren't being closed which causes FDs to slow be drained. If the OP can get a goroutine profile of `lnd`, then should be clear if there're a lot of lingering RPC goroutines around.

**Comment by apotdevin** [comment]
Thanks to some help from @alexbosworth, I realised I was creating new LND connections for every request. Fixed it and now the connection is reused. This should help with this issue. Fix will go in with the next release

**Comment by apotdevin** [comment]
It's now in release 0.11.0 :)

**Comment by Kixunil** [comment]
Running the tests right now. :)

**Comment by Kixunil** [comment]
Even after running it for a while and clicking around the descriptors seem to stay low. I consider this fixed. Should this issue be closed?

**Comment by apotdevin** [comment]
Will close it then :)
