### ISSUE TITLE
[Feature request] connect to the external APIs through Tor or other proxy

### ISSUE THREAD

**Issue by openoms** [apotdevin/thunderhub#175]
**Is your feature request related to a problem? Please describe.**
https://t.me/thunderhub/5454
>When logging into lnmarkets, from where is it getting the IP data? Running thunderhub on mynode, so apologies if this question is better suited for mynode. Would have thought it was running behind tor, but the "Last IP" on the lnmarkets page in thunderhub after logging in is the naked ip

**Describe the solution you'd like**
connect to the external APIs through Tor other proxy

**Describe alternatives you've considered**
Simply torifying the process fails: https://github.com/rootzoll/raspiblitz/pull/1819

**Provide examples**
Loop has native --proxy support; https://github.com/rootzoll/raspiblitz/blob/077ee8b6ad82d78a69c2f4ae7e493ba5dfbbfcfd/home.admin/config.scripts/bonus.loop.sh#L97

EDIT: torifying the process works with the right settings. See: https://github.com/rootzoll/raspiblitz/pull/1819#issuecomment-739554259

**Comment by Kixunil** [comment]
Would be great for other requests as well, it's the main reason I disable various APIs in my repository by default.

**Comment by apotdevin** [comment]
You can now proxy all external requests through TOR: 5bcfed1b248c060a10bc0461e9cd0b81fe5bf779

https://github.com/apotdevin/thunderhub#tor-requests
