### ISSUE TITLE
Adding Bos Score

### ISSUE THREAD

**Issue by bota87** [apotdevin/thunderhub#181]
It can be usefull to show, and maybe monitor the change over time, the [bos score](https://github.com/openoms/lightning-node-management/blob/master/BosScore.md) of the node.

The current score can be taken from this [json](https://nodes.lightning.computer/availability/v1/btc.json)

It can be realy useful to show the score of the others connected node since they can impact my node score.

**Comment by apotdevin** [comment]
Thanks for the feature request! I like the idea 👌

**Comment by apotdevin** [comment]
BOS Scores added in version 0.12.0 👍
