### ISSUE TITLE
Base fee of 0 not respected in UI (reset to 1 after updating details)

### ISSUE THREAD

**Issue by cryptoteun** [apotdevin/thunderhub#183]
**Describe the problem/bug**
I have base fee set to 0 via lncli (because of #157). But when I want to update the channel details the base fee is resetted to 1, even when I didn't touch it.

**Your environment**
* Version of ThunderHub: 0.11
* Deployment method: Docker
* Other relevant environment details:

**To Reproduce**
1. Set base fee to 0 via lncli
2. Go to Channels
3. Select a channel with base fee 0
4. Click on "Update Details"
5. Base Fee is shown like "sats"
6. Update Fee Rate
7. Click Update Channel Details

**Expected behavior**
Base Fee setting isn't changed, and should be 0.

**Actual behavior**
Base Fee setting is changed, and is set to 1.

**Comment by apotdevin** [comment]
Thanks for opening the issue!

**Comment by apotdevin** [comment]
Closed by https://github.com/apotdevin/thunderhub/pull/193

**Comment by cryptoteun** [comment]
Thanks for the fix @apotdevin , I guess #157 can be closed as well ?
