### ISSUE TITLE
Error Creating Claim Transaction 

### ISSUE THREAD

**Issue by thecharacter** [apotdevin/thunderhub#195]
I attempted to swap from Lightning BTC to BTC. In the Swap history section it says ready to claim. When I click claim and enter a satoshi amount I get "ErrorCreatingClaim Transaction". I restarted the app and swap history is blank. What happens when a swap is not claimed?

Im using Thunder Hub 0.12.1 on my Raspiblitz. Everything is synced. 

![Screen Shot 2020-12-24 at 5 41 37 PM](https://user-images.githubusercontent.com/70460811/103113443-93058b80-460f-11eb-9397-a2f2f00dd66d.png)
![Screen Shot 2020-12-24 at 5 42 02 PM](https://user-images.githubusercontent.com/70460811/103113446-96991280-460f-11eb-8423-05624c58e677.png)
![Screen Shot 2020-12-24 at 5 42 15 PM](https://user-images.githubusercontent.com/70460811/103113449-9862d600-460f-11eb-82be-1e5e9ac5ad1e.png)

**Comment by apotdevin** [comment]
Can reproduce locally, working on a fix 👍  Thanks for opening the issue

**Comment by apotdevin** [comment]
Fixed by: https://github.com/apotdevin/thunderhub/pull/196
