### ISSUE TITLE
List with nodes outside the bos list

### ISSUE THREAD

**Issue by bota87** [apotdevin/thunderhub#199]
I'm looking for a way to find the nodes I'm connected to which are not in the bos list.
Maybe this can be added in the scores page? Also on that page can be useful to highlight the nodes to which I'm connected

**Comment by apotdevin** [comment]
In version 0.12.3 you should now see the BOS scores for the nodes you have a channel with in the channels view.

You can also see scores for particular nodes by going to the url `/scores/[NODE PUBLIC KEY]`. Will add a feature to see the scores without needing to use the url in a future release

**Comment by bota87** [comment]
First of all great job! :thumbsup:
I still have some bug/features requests:
1. My node is in the bos list but actualy I see this message on top of the scores page (This node is not in the BOS list. Read more about these scores here.)
2. A thousands separator can make easy to read the score value on the scores and history page
3. On the historical scores list and graph the current value is not available
4. On the channels page the score is not referred to the current value

**Comment by apotdevin** [comment]
Thanks!

1. Could it be that your node was not on that days bos list?
2. Added this! Thanks for the suggestion
3. historical scores update every few hours so there might be a point where the last one is missing
4. How I though about it is that if the node has been in the bos list any day in the past week it will appear as a "BOS node" and the date of the score will appear also below the score. What do you think about this?

**Comment by bota87** [comment]
1. I'm tring with the last version (0.12.5), I can search and find my node on the scores page but the message is still there
2. It was a pleasure! The next step could be localize the decimals and thousands separators, but this deserve a new issue
3. Ok it's not a problem
4. I think it may be the same reason as point 3

**Comment by bota87** [comment]
After upgrading to 0.12.6 the "node is not in the BOS list" message is disappeared and I can see my score and position!
