### ISSUE TITLE
Docker ?

### ISSUE THREAD

**Issue by iangregsondev** [apotdevin/thunderhub#2]
Hi,

I notice it states there is a docker file for easy deployment. I couldn't find it.

I would love to add it to my current setup - i am using a docker compose file.

I tried searching also on docker hub.

Can you point me in the right direction ?

Thanks

**Comment by apotdevin** [comment]
Hi, a docker image will come as a future feature but it isn't currently available. Will try to find the time to get this done, sorry for that.

**Comment by iangregsondev** [comment]
No worries, thanks for the update. It certainly looks very promising.

**Comment by apotdevin** [comment]
Hi, so have an initial setup for docker deployments with docker-compose. Still a WIP but you can see the PR here: https://github.com/apotdevin/thunderhub/pull/3
