### ISSUE TITLE
Clearer description: Max Rebalance vs. Target Amount

### ISSUE THREAD

**Issue by STAWKEYE** [apotdevin/thunderhub#204]
When using the Rebalance/Advanced/Detailed feature, I am unsure of the definition of some criteria. Perhaps tooltip popups with descriptors on each?

Is Max_Fee the total fee, or only the max base fee? It's unclear since it's followed by Max_Fee_Rate, implying that the previous field referred to base fee.

I had assumed Max_Rebalance was the maximum number of sats you want to push in the circular payment,

Is Target_Amount the ideal target of Max_Rebalance or does it represent the ideal final local balance of a particular channel? Using example numbers, am I saying "I want to send 2000 sats in a circular payment" or am I saying "I want to send a circular payment that leaves me with 2000 local sats"?

**Comment by apotdevin** [comment]
Hey! Definitely need to change the rebalancing view. This has been on the list for a while, might get this fixed up next!

The questions really help me clarify what should be better explained, thanks for that!

**Comment by apotdevin** [comment]
Hey! This view has since been refactored and should be more straight forward to follow :) Closing this but feel free to reopen if you still have concerns
