### ISSUE TITLE
Update available indicator

### ISSUE THREAD

**Issue by decentralizedb** [apotdevin/thunderhub#208]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Some indicators let us know that an app update is available could be a great feature, and if it was possible to click the button and update the app, that would be great!

**Describe alternatives you've considered**

**Provide examples**
If applicable provide examples, wireframes, sketches or images to better explain your idea.

**Additional context**

**Comment by apotdevin** [comment]
Duplicate of https://github.com/apotdevin/thunderhub/issues/209
