### ISSUE TITLE
Can't represent invoices greater than MAXINT sats

### ISSUE THREAD

**Issue by YadrachistyIzumrud** [apotdevin/thunderhub#210]
**Describe the problem/bug**
If it is invoice with big amount of satoshis (i.e. 100BTC=10000000000sats), transactions page stucks with exception

**Your environment**
Version of ThunderHub: 0.12.4 and below, lnd version 0.11.1-beta commit=v0.11.1-beta

**To Reproduce**
1. Create invoice for 100BTC with BlueWallet
2. Go to transactions page
3. See error "Int: cannot represent non 32-bit signed integer value: 10000000000" and no invoices as expected

I think, amount must be unsigned int64 type

**Comment by apotdevin** [comment]
I want someone to pay a 100btc invoice from me 😔

Regardless thanks for finding the bug! This is now fixed with d10b2120b59888366bbffde6f41682307254af38 and will be in the next release

**Comment by Kixunil** [comment]
Is this related to #122? Maybe both are fixed?

**Comment by apotdevin** [comment]
Ah think that one is related to the wallet balance while this was for the invoice/payment amounts.

Will get the other in as well for the next release 👍

**Comment by apotdevin** [comment]
Closing but feel free to reopen if theres some issue with it still!
