### ISSUE TITLE
Continuously attempt rebalance until successful

### ISSUE THREAD

**Issue by MaxHillebrand** [apotdevin/thunderhub#217]
**Is your feature request related to a problem? Please describe.**
Re-balancing a channel often fails. It has to be re-attempted multiple times with different routes until it finally succeeds. Currently this is done in 4 user steps, but it can be automated.

**Describe the solution you'd like**
Take user input:
- out-going channel
- incoming channel
- max fee
- max parts
- timeout

then under the hood and without any further user input:
- query route
- if below max fee, then
- initiate send
- if route unsuccessful, then
- query next route and repeat, until
- re-balance successful, or
- timeout is reached

**Comment by apotdevin** [comment]
Hey! Thanks for opening the ticket. Which version are you running? On the latest (0.12.6) the rebalancing has changed to be more persistent in looking for ways to rebalance

**Comment by MaxHillebrand** [comment]
I'm running @kixunil debian repo, thus at `0.11.1-1`.

**Comment by apotdevin** [comment]
Closing this ticket for house cleaning, latest versions have a better rebalancing
