### ISSUE TITLE
Manually set payment amount for invoice with 0 amount

### ISSUE THREAD

**Issue by MaxHillebrand** [apotdevin/thunderhub#218]
**Is your feature request related to a problem? Please describe.**
When the receiver offers a `0 amount` / custom amount invoice, there is no user input in thunderhub to set the desired payment amount.

**Describe the solution you'd like**
When 0 amount invoice detected, add a new textbox input for sat amount.

**Comment by apotdevin** [comment]
Thanks for the request! Never tried a 0 amount invoice, will check it out 👍

**Comment by Kixunil** [comment]
I disagree witth the solution. The UI should display a big fat warning that the invoice is dangerous. Maybe allow it after user clicks "I understand that the whole amount may be stolen" (Strictly speaking whole payment-1msat, but I think it's negligible.)

I've seen something about a safer version of invoices but not sure if it's already implemented and supported. Better stay on the safe side or investigate.

**Comment by apotdevin** [comment]
Will close for now because of the security concerns mentioned above.
