### ISSUE TITLE
Rebalance Doesn't Work

### ISSUE THREAD

**Issue by mlewk** [apotdevin/thunderhub#224]
Whenever I try to preform a rebalance I am unable to do so no matter the fee amount, and it is saying failedtofindpathbetweenpeers even with high Fee amount and Fee Rate while using common nodes such as LNBIG, BitRefill, ACINQ, Breez, etc. How do I resolve this balance issue?

**Comment by apotdevin** [comment]
Hey! Thanks for opening the ticket, will look into it. ThunderHub uses BalanceOfSatoshi behinds the scenes to do the rebalancing. Might be that something changed with when updating the version.

**Comment by mlewk** [comment]
Thanks, please keep me updated!

**Comment by apotdevin** [comment]
You can now set both fee and fee rate when rebalancing in the latest version. Let me know if it works!

**Comment by mlewk** [comment]
I still am unable to rebalance the channels. It says feelimittoohigh no matter how high I set the base of rate

**Comment by definitivequestion** [comment]
You need to set a base fee rate AND the ppm rate. I have seen LOOP charge 3% plus 10 satoshi. I have other peers that are charging 100% in fees because I don't fit their criteria.

**Comment by mlewk** [comment]
oh wow, 100% seems quite high for fees. How do I route my balance so that it is minimal fees?

**Comment by apotdevin** [comment]
Hi, doing some house cleaning so will close this ticket. Rebalancing is weird, it sometimes works, sometimes doesn't, there's no magic formula for it unfortunately
