### ISSUE TITLE
Feature request: In Transactions tab, show which channel absorbed payment

### ISSUE THREAD

**Issue by beeforbacon** [apotdevin/thunderhub#235]
I would like to be able to see which channels are absorbing payments for my merchant service in order to facilitate better understanding of traffic flow through my node. The solution I propose is to have the information available in the transactions menu in the transactions list also include "incoming channel" perhaps for a transaction receipt along with the minutes-ago and the time- amount: 
 
![image](https://user-images.githubusercontent.com/51864803/114153347-38a5e780-98ed-11eb-9385-556506fecc99.png)

So, in the image above maybe also include the channel that absorbed the payment, and maybe have an area that, just like the most routed is presented in the forwarded menu, but this shows the most received into. Hope that makes sense. Thank you for all your hard work and for a great tool.

**Comment by apotdevin** [comment]
Would be very nice! Thanks for opening the ticket!

**Comment by apotdevin** [comment]
Should be now in version 0.12.13, let me know if it works!
