### ISSUE TITLE
Add different filtering options to the transactions

### ISSUE THREAD

**Issue by beeforbacon** [apotdevin/thunderhub#239]
Feature Request: 
I would like to be able to see only completed transactions (hide all expired invoices) in the transactions tab, to better see activity at a glance. Perhaps a toggle at the top that hides expired invoices from the list, perhaps near where the red color is on the following screenshot. thank you! 

![image](https://user-images.githubusercontent.com/51864803/114280262-6cc0fb80-9a06-11eb-9ce1-3310d947cc0c.png)

**Comment by mutatrum** [comment]
A secondary option would be to filter out circular rebalances. They currently show up as two transactions with the same id: one payment toward my own node, and a receive. Moving these out of the transactions list and moving them to the rebalance page would be really helpful. A bonus would be to add an aggregated circular rebalance count/token/fee graph.

**Comment by apotdevin** [comment]
This is now available in the latest version. You can filter unpaid invoices and circular payments
