### ISSUE TITLE
Details page keeps loading

### ISSUE THREAD

**Issue by lessless** [apotdevin/thunderhub#240]
**Describe the problem/bug**
Details page doesn't open up on freshly installed TH

**Your environment**
* Version of ThunderHub: 0.12.13
* Deployment method:  RaspiBLitz 1.7RC2

**To Reproduce**
1. Go to  `/details`
2.  The page itself loaded but "loading" indicator keeps going

**Expected behavior**
Details page should load

**Actual behavior**
Details page keeps showing a loading indicator 

**Additional context**
I would love to take a look at the logs but I don't know where to find them. 
I'm running TH as a part of RaspiBlitz and it's started as `node /home/thunderhub/thunderhub/node_modules/.bin/next start -p 3010`.

**Comment by apotdevin** [comment]
Hi! Thanks for opening the ticket, this is now fixed in commit 1519986d387981568886c158cf9d69b6680d233a
