### ISSUE TITLE
Add ability to not use sats symbol

### ISSUE THREAD

**Issue by benthecarman** [apotdevin/thunderhub#243]
The sats symbol isn't apealing to me and would like to have the option to just use the word "sats" like before.

**Comment by apotdevin** [comment]
Hey! Thanks for the request, there's now a unit toggle with commit 62d8db5456e67aa3433946f8f4fa2335a944d5b6

Should be in the next version

**Comment by benthecarman** [comment]
Where is the option to turn this on, I don't see it

**Comment by apotdevin** [comment]
Settings > interface

**Comment by benthecarman** [comment]
I don't see how to do it

![image](https://user-images.githubusercontent.com/15256660/116894654-ec9e4800-abf7-11eb-9226-8052a289f725.png)

**Comment by apotdevin** [comment]
I think you arent on the latest version, are you building the app yourself?

**Comment by benthecarman** [comment]
> I think you arent on the latest version, are you building the app yourself?

Yeah, I am running off of latest `master`

**Comment by apotdevin** [comment]
hmm can you try stopping the app and rebuilding?

**Comment by benthecarman** [comment]
> hmm can you try stopping the app and rebuilding?

Ah got it, thank you
