### ISSUE TITLE
Year 2021 is not an option in the accounting report screen

### ISSUE THREAD

**Issue by Chris869218** [apotdevin/thunderhub#252]
When creating an accounting report, the only year options are 2017, 2018, 2019, 2020. If current year exports are expected to take place from another screen, that's not abundantly clear. 

**Your environment**
* Version of ThunderHub: 0.10.4
* Deployment method: lnd (on raspiblitz)

**To Reproduce**
Tools --> Create report (under Accounting)

**Expected behavior**
I'd expect to see 2021 as an option, or, some message that directs the user where they can export invoices from the current year to date. 

**Actual behavior**
If I select 2020 (to see if perhaps 2021 transactions would be included as well), no 2021 invoices get exported.

**Comment by DocBrown101** [comment]
I guess you need to update you TH version. With version 0.12.17 everything is displayed correctly.

![image](https://user-images.githubusercontent.com/11892773/120764756-c7fbff80-c518-11eb-8808-aff9586c7446.png)

**Comment by Chris869218** [comment]
Thanks. Fixed.
