### ISSUE TITLE
Differentiate between public and private channels

### ISSUE THREAD

**Issue by ProofOfKeags** [apotdevin/thunderhub#258]
**Is your feature request related to a problem? Please describe.**
I am frustrated that I don't know from Thunderhub which of my channels are public.

**Describe the solution you'd like**
I would like to be able to see in the channel listing page which channels are private and which ones are public. Ideally this would even be a "tabbed" list where you could filter out all public or all private channels respectively.

**Describe alternatives you've considered**
An alternative would be just an indicator similar to how RTL works where it shows in the list which ones are private and public as a column entry.

**Comment by apotdevin** [comment]
In the channel view there is an `eye` indicator to show if a channel is private. It won't show if you are in the `ultra compact` layout but the other layouts should have it

**Comment by ProofOfKeags** [comment]
You think thered be any convenient way to keep that info around even in ultracompact mode? I honestly only work in ultracompact which is why I didn't notice this.
