### ISSUE TITLE
Total balance does not exclude commit fees

### ISSUE THREAD

**Issue by 7hacker** [apotdevin/thunderhub#261]
The total balance on Thunderhub UI appeared to fluctuate and I couldnt find any onchain payments, I didnt generate any LN invoices and I didnt perform any forwards that would account for the fluctuations. On closer inspection it seems that Thunderhub does not omit the commit fees while tools like bos do

For example:

```
bos 7.18.2

   USAGE

     bos balance

     Sums balances on-chain, in channels, and pending, minus commit fees
```

On https://lightningwiki.net/index.php/Fees :

```
The balance fluctuates because commit fees for channels get renegotiated as the cost to publish to the bitcoin blockchain changes. When the commit fees rise (btc fees become more expensive) some of your local balance is reserved to meet those fees, resulting in your local balance dropping. When fees drop the reverse happens.

To avoid this issue what you want to do is sum all your channel local balances with the commit fees for only the channels you have opened. There is currently no easy way to tell if you opened a channel or not but there was just a PR in lnd for example to make this easier on developers. Right now the solution I am using is to infer whether or not I opened a channel by its sent, received, and local balance.
```
Also to make things simpler, I have no pending channel opens or closes and I found:

`bos balance output + commit fees on thunderhub UI = total balance on thunderhub UI
`

Spoke to @apotdevin on Telegram regarding this issue

**Comment by apotdevin** [comment]
Fixed this in the latest version! Thanks for opening the ticket
