### ISSUE TITLE
[Feature request] Set channel fees at open dialog and on pending channels

### ISSUE THREAD

**Issue by mutatrum** [apotdevin/thunderhub#273]
**Is your feature request related to a problem? Please describe.**
For custom fees on a new channel, one has to wait until the open tx is confirmed plus 3 (IIRC) blocks, before one can change the fees.

**Describe the solution you'd like**
Ideally, a possibility to pre-set custom fees on the open dialog screen, and on the pending channel screen. As soon as the channel gets active, the fees need to be applied. This is especially useful for draining channels such as LOOP.

**Describe alternatives you've considered**
Waiting and staring at mempool.space. Scripting it myself, but that seems overfill as TH has most of the infrastructure there.

**Comment by apotdevin** [comment]
This isn't supported by LND and Thunderhub isn't listening to events currently so no way for it to know when a channel has been opened to set the fees. You can change the default fee in the lnd.conf file
