### ISSUE TITLE
[Feature request] Option to generate own/various LNURL-pay

### ISSUE THREAD

**Issue by Darth-Coin** [apotdevin/thunderhub#275]
**Is your feature request related to a problem? Please describe.**
Is not related to a problem. Just a new useful feature to generate own LNurl-pay address(es)

**Describe the solution you'd like**
Sometimes you need a quick solution to receive donation, fix amount of sats, product fix price in sats and in order to avoid mumbling around installing another apps/servers/extensions etc, a simple way to be at hand, that users already have installed TH, is to generate their own LNURLs. Would be nice to have multiple LNURLs (if is possible) and a system of labeling of each.

**Describe alternatives you've considered**
LNBits, lntxbot offer alternative, but those are not linked with user node/wallet directly.

**Provide examples**
Maybe I have multiple websites where I want to have for each a LNURL for donations/payments

**Comment by apotdevin** [comment]
Hey, not possible to include in Thunderhub since most people don't have it available over clearnet. Check out this project for this https://github.com/apotdevin/NextPay
