### ISSUE TITLE
Close channel not using the correct fee rate

### ISSUE THREAD

**Issue by benthecarman** [apotdevin/thunderhub#281]
I closed a channel and entered a 1 sat/vbyte and the resulting tx had a 4 sat/vbyte fee rate. Maybe a conversion from sats/weight is being done wrong?

**Comment by Deekee62** [comment]
This doesn't seem to be a ThunderHub issue as it also happens, when you close the channel using RTL and even the CLI

**Comment by apotdevin** [comment]
This comes from LND, I think it has something to do with how they sweep transactions but not sure to be honest
