### ISSUE TITLE
Node names are not wrapping in channel view

### ISSUE THREAD

**Issue by Deekee62** [apotdevin/thunderhub#285]
**Describe the problem/bug**
Node names are not wrapping in channel view

**Your environment**
* Version of ThunderHub:0.12.19
* Deployment method:Umbrel 
* Other relevant environment details:Raspberry Pi 4

**To Reproduce**
1. Go to 'Channels'
2. See channel list

**Expected behavior**
Channel names should wrap, therefore long node name can be seen

**Actual behavior**
Channel names don't wrap, therefore long node names can't be seen completely, especially when they have all the same prefix it's hard to see which node it actually is

**Screenshots/Links**
![telegram-cloud-photo-size-1-5089547696599050552-y](https://user-images.githubusercontent.com/33904339/123385645-0cb60c00-d596-11eb-84b0-3c24508f0581.jpg)

**Additional context**

**Comment by apotdevin** [comment]
Hey! Thanks for the suggestion, I increased the size of the text in the latest release
