### ISSUE TITLE
Reduce size of dependencies from ~430MB

### ISSUE THREAD

**Issue by ProofOfKeags** [apotdevin/thunderhub#287]
There seems to be way too much bloat in the dependency tree causing the node_modules folder to take up nearly half a gigabyte. This seems excessive.

A cursory glance through the package.json reveals some stuff that ought to be in the dev-dependencies set, but I'm not sure. The main one that jumps out at me is `typescript` but I'm not sure how many others could afford to be moved to dev-dependencies.

**Comment by apotdevin** [comment]
Hey! I cleaned up the dependencies a bit, let me know if you see anything else that can be optimized. Thanks for opening the suggestion!

**Comment by ProofOfKeags** [comment]
Unfortunately I can't test anything now because everything after 0.12.17 is broken for me. I'm opening a separate issue on it.
