### ISSUE TITLE
Support Private Routing Hints

### ISSUE THREAD

**Issue by ProofOfKeags** [apotdevin/thunderhub#298]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to use private channels with thunderhub because routing hints are not supported. 

**Describe the solution you'd like**
When generating a lightning invoice, you should be able to include all private channels or ideally pick a specific one that you would like to embed in the invoice.

**Comment by ProofOfKeags** [comment]
This should be relatively straight forward as it is just a flag in the `addinvoice` call.

```
NAME:
   lncli addinvoice - Add a new invoice.

USAGE:
   lncli addinvoice [command options] value preimage

CATEGORY:
   Invoices

DESCRIPTION:
   
  Add a new invoice, expressing intent for a future payment.

  Invoices without an amount can be created by not supplying any
  parameters or providing an amount of 0. These invoices allow the payee
  to specify the amount of satoshis they wish to send.

OPTIONS:
   --memo value              a description of the payment to attach along with the invoice (default="")
   --preimage value          the hex-encoded preimage (32 byte) which will allow settling an incoming HTLC payable to this preimage. If not set, a random preimage will be created.
   --amt value               the amt of satoshis in this invoice (default: 0)
   --description_hash value  SHA-256 hash of the description of the payment. Used if the purpose of payment cannot naturally fit within the memo. If provided this will be used instead of the description(memo) field in the encoded invoice.
   --fallback_addr value     fallback on-chain address that can be used in case the lightning payment fails
   --expiry value            the invoice's expiry time in seconds. If not specified an expiry of 3600 seconds (1 hour) is implied. (default: 0)
   --private                 encode routing hints in the invoice with private channels in order to assist the payer in reaching you
```

**Comment by oxbased** [comment]
This is necessary for nodes with only private channels to receive funds. 

Here is a good UX example from Zap in a discussion how BTCPayserver added this option. https://github.com/btcpayserver/btcpayserver/issues/1480#issuecomment-626370964

**Comment by oxbased** [comment]
Looks like thunderhub uses ln-service. [Here is the ln-service 'createInvoice' function](https://github.com/alexbosworth/ln-service#createInvoice) that has a parameter 'is_including_private_channels' which I believe is what's needed to include the route hints for private channels. 

Here is the thunderhud server code calling lnd to create invoice. https://github.com/apotdevin/thunderhub/blob/master/server/schema/invoice/resolvers.ts#L81

**Comment by ProofOfKeags** [comment]
I could probably tackle this were it not for the UI components. I might still take a stab at it though.

**Comment by apotdevin** [comment]
Any disadvantage you guys see for just enabling as default?

**Comment by apotdevin** [comment]
Ok, I read the linked BTCPay conversation 👍  I'll enable the toggle

**Comment by apotdevin** [comment]
Fixed in https://github.com/apotdevin/thunderhub/pull/304
