### ISSUE TITLE
Runtime Error in BarChart.tsx

### ISSUE THREAD

**Issue by kwuenscher** [apotdevin/thunderhub#302]
**Describe the problem/bug**
Getting a runtime error:

```
Unhandled Runtime Error

TypeError: can't convert undefined to object

src/components/chart/BarChart.tsx (92:22) @ Chart

  91 | 
> 92 |   const keys = Object.keys(data[0]).filter(d => d !== 'date');

```
On a freshly setup node. I haven't looked further into whether data can be an empty array or not but checking this before filtering for elements and returning keys=[] fixes the problem. Annoyingly the entire app crashes even though all other data loads properly. So I don't think its a data retrieval problem. 

Also I'm connecting to a LND node `v0.13.1-beta`. 

**Your environment**
master
* Deployment method: 
yarn dev

**Comment by apotdevin** [comment]
Checking! it thanks for opening the ticket

**Comment by kwuenscher** [comment]
Great thanks - changing line 92 to. 
``` 
  const keys =
    data.length > 0 ? Object.keys(data[0]).filter(d => d !== 'date') : [];
```
fixed it for me.

**Comment by apotdevin** [comment]
I just pushed a change, mind checking if it fixes it for you? Unfortunately I haven't been able to reproduce locally

**Comment by kwuenscher** [comment]
Yes, works now, thanks! :pray:
