### ISSUE TITLE
Total node balance to stay fixed

### ISSUE THREAD

**Issue by imirkth** [apotdevin/thunderhub#313]
**Is your feature request related to a problem? Please describe.**
in version 0.12.24, the balance on lightning moves based on your channels being online / offline. it stresses me out.
is it possible to show a constant balance based on the amount when all peers are online

**Describe the solution you'd like**
Keep the balance constant or at least show the total amount on the node to stay consistent even if channels become red.

**Additional context**
that would make my blood pressure stay more constant :-) specially with btc prices going up.

Thanks for considering it.

**Comment by apotdevin** [comment]
Balances are now displayed differently in version `0.12.27`
