### ISSUE TITLE
Fiat currency values not updated when sidebar is collapsed

### ISSUE THREAD

**Issue by super-e** [apotdevin/thunderhub#340]
**Describe the problem/bug**
Hi, when the navigation bar is collapsed, clicking on the display currency will cycle sats->BTC->Eur->Usd but the values on the main frame will only be updated for sats and BTC, Eur and Usd cases instead will show values and symbols of sats.

**Your environment**
* Version of ThunderHub: v.0.12.17
* Deployment method: MyNode auto-deployment

**To Reproduce**
1. Collapse navigation bar
2. Click repeatedly on currency icon 
3. Notice how the amounts and symbols on the main frame not always correspond to the current currency selection (in particular for fiat currencies)

**Expected behavior**
The values and currency symbol should always reflect the current currency selection, automatically updating at each press of the currency button, exactly as it happens when the navigation bar is not collapsed and the currency is selected from the list of currency icons.

**Actual behavior**
Values and symbols are updated only for sats and BTC, for fiat currencies instead they fall-back to the sats case.

**Screenshots/Links**
Not applicable.

**Additional context**
Tried only with the deep night (star) colour theme, you might want to compare if the behaviour is the same for the other two colour schemes.

**Comment by apotdevin** [comment]
Thanks for the ticket! Fixed in version `0.12.27`
