### ISSUE TITLE
ExpectedCommitmentTypeInChannelMessage after upgrading LND to v0.14.0

### ISSUE THREAD

**Issue by wchancao** [apotdevin/thunderhub#360]
**Describe the problem/bug**
Thunderhub shows balances at zero for onchain and offchain, and clicking on Channels shows `ExpectedCommitmentTypeInChannelMessage` after upgrading LND to v0.14.0

**Your environment**
* Version of ThunderHub: 0.12.30
* Other relevant environment details: Raspiblitz v1.7.1

**To Reproduce**
1. Go to http://localhost:3010 and Log in
2. Click on Channels
3. See error

**Additional context**
RTL shows balances and channels Ok so gotta be some issue with Thunderhub

**Comment by vafanassieff** [comment]
Working ok in `v0.12.31`

**Comment by wchancao** [comment]
Confirmed. Thanks!
