### ISSUE TITLE
Feature request: allow YML_ENV to be used for master password

### ISSUE THREAD

**Issue by AaronDewes** [apotdevin/thunderhub#361]
**Is your feature request related to a problem? Please describe.**
YML_ENV currently can't be used for masterPassword. Allowing to use this as a password would help increase security in prebuilt nodes like Umbrel or citadel without the need for app-specific workarounds.

**Describe the solution you'd like**
YML_ENV should be available in the global scope of thubConfig.yaml.

**Describe alternatives you've considered**
App-specific workarounds with sed like in Umbrel would be possible too, but are less convenient.

**Comment by apotdevin** [comment]
Hey! Theres a new env var `MASTER_PASSWORD_OVERRIDE` that you can set that will have priority over the `masterPassword` field in the yaml file

**Comment by AaronDewes** [comment]
Thanks! I'll update this in Citadel then.

**Comment by apotdevin** [comment]
Hasn't been released yet but you can test it by pulling the latest master branch changes
