### ISSUE TITLE
.env file path and log file path for docker run

### ISSUE THREAD

**Issue by emplexity** [apotdevin/thunderhub#371]
**Describe the problem/bug**
The documentation and issues list are ambiguous regarding the path where to place the .env file when thunderhub is deployed with docker. Ambiguous as well regarding whether this file should be named .env or .env.local.

There is no location where to look for the log file, there is no log entry presented on screen when launching via Docker

Many trials & errors  placing the .env file in top directory, in /thunderhub, in the home/yyyyy user directory, in ~/thunderhub were all unsuccessful: when accessing http://myremotecomputer:3000 the login screen shows up saying that "To start you must create an account on your server. You can find instructions for this here." 

What to do to resolve this?

The .env file content is:
# -----------
# Account Configs
# -----------
ACCOUNT_CONFIG_PATH = '/home/yyyyy/ThunderHub/thubConfig.yaml';

The thubConfig.yaml content is:
masterPassword: 'xxxxxxxx' 
defaultNetwork: 'mainnet'
accounts:
  - name: 'yyyyy'
    serverUrl: '0.0.0.0:10009'
    lndDir: '/home/yyyyy/.lnd'

**Your environment**
* Version of ThunderHub: 0.12.31
* Deployment method: docker
* Other relevant environment details: VPS ubuntu 16.04 

**To Reproduce**
1. place .env somewhere'
2. docker run
3. http://myremotecomputer:3000
4. error message ""To start you must create an account on your server. You can find instructions for this here." 

**Expected behavior**
Expect to:
1. enter Thunderhub after http://myremotecomputer:3000 and entering password as set in thubConfig.yaml
2. find a log file to trace the issue that thunderhub faces to find the server account from the .env and thubConfig.yaml files
3. have an explicit specification of the path and name for .env and .env.local and log files in the case of a docker deployment.

**Comment by emplexity** [comment]
After more trials and as many errors, passing -e ACCOUNT_CONFIG_PATH on the docker run command, the log of the server shows that the server does not find the file. However "cat" finds the file at the specified path. At the same time, the client reports that "To start you must create an account on your server. You can find instructions for this here."
Same behaviour if the .env file is passed with the --env-file parameter as an argument to the docker run command.

What should I do to have the container working with the environment as specified in the .env file that I placed in the ~/thunderhub directory?


xxx@yyy:~$ sudo docker run --rm -it -d -e ACCOUNT_CONFIG_PATH='/home/xxx/ThunderHub/thubConfig.yaml' -p 3000:3000/tcp apotdevin/thunderhub:v0.12.31
3a02c89aaea680e6e44f74aa3979354d113f21de14e42fd3a4f46f34ee23897f
xxx@yyy:~$ sudo docker container ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS          PORTS                                       NAMES
3a02c89aaea6   apotdevin/thunderhub:v0.12.31   "docker-entrypoint.s…"   37 seconds ago   Up 35 seconds   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   ecstatic_davinci
xxx@yyy:~$ sudo docker container logs 3a02c89aaea6

> thunderhub@0.12.31 start /app
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
2022-01-02 17:04:31 error [THUB]: No file found at path: /home/xxx/ThunderHub/thubConfig.yaml
2022-01-02 17:04:31 info [THUB]: No account config file found at path /home/xxx/ThunderHub/thubConfig.yaml
2022-01-02 17:04:31 error [THUB]: No file found at path: /home/xxx/ThunderHub/thubConfig.yaml
2022-01-02 17:04:31 info [THUB]: No account config file found at path /home/xxx/ThunderHub/thubConfig.yaml
xxx@yyy:~$ cat /home/xxx/ThunderHub/thubConfig.yaml
masterPassword: 'my_password' 
defaultNetwork: 'mainnet'
accounts:
  - name: '[xxx]'
    serverUrl: '127.0.0.1:10009'
    lndDir: '/home/xxx/.lnd'
xxx@yyy:~$

**Comment by bota87** [comment]
Hi @emplexity,
let me know if you resolve, I'm looking for the same

**Comment by bota87** [comment]
ok after some pain I have a functional setup!
```
docker run -d --restart unless-stopped \
	-p 3000:3000/tcp \
	--add-host=host.docker.internal:host-gateway \
	-e LOG_LEVEL='warn' \
	-e ACCOUNT_CONFIG_PATH="/config/thubConfig.yaml" \
	--mount type=bind,source="/home/bitcoin/thunderhub",destination=/config \
	--mount type=bind,source="/home/bitcoin/.lnd",destination=/lnd \
	--name thunderhub \
	apotdevin/thunderhub:v0.13.6
```
in the /home/bitcoin/thunderhub/thubConfig.yaml file
```
masterPassword: mypassword
accounts:
  - name: mynodename
    serverUrl: 'host.docker.internal:10009'
    lndDir: /lnd
```
finally if you have ufw enabled like me you have to open the gRPC port from the docker network
`sudo ufw allow from 172.17.0.0/16 to any port 10009`


@apotdevin can you add the latest tag on Docker Hub to simplify the run command?

**Comment by emplexity** [comment]
@bota87 thanks.
Regarding the additional rule for UFW, how can we restrict it to the private ip address 172.17.0.0/16 as not to risk to open an unwanted access from a public 172.17.0.0/16 IP address?

**Comment by bota87** [comment]
Maybe this ufw rule can be safest
`sudo ufw allow in on docker0 to any port 10009`

**Comment by emplexity** [comment]
@bota87 thanks once more! Much appreciated.
The internet shows reports about the so call UFW docker security flaw ([https://github.com/chaifeng/ufw-docker](url)). I understand that the default of the docker -p parameter is to open the ports of a container to the public network bypassing UFW rules. This might apply to the 3000 and 10009 ports of thunderhub.
As lnd runs on mainnet, I wish to access thunderhub exclusively via a vpn as to avoid exposing to the public ports used only for administration. 
The link above proposes a fix for this. I will study it further to see what can be done without compromising unduly the security of the lnd node.

**Comment by bota87** [comment]
For my setup I use `-p 127.0.0.1:3000:3000/tcp` so the port is accessible only on localhost

**Comment by emplexity** [comment]
@bota87 , worked for me with the following variation, thanks
sudo docker run -d --rm \
	--network host \
	-e LOG_LEVEL='warn' \
	-e ACCOUNT_CONFIG_PATH="/config/thubConfig.yaml" \
	--mount type=bind,source="/home/xxxxxx/thunderHub",destination=/config \
	--mount type=bind,source="/home/xxxxxx/.lnd",destination=/lnd \
	--name thunderhub \
	apotdevin/thunderhub:v0.13.6

with the thubConfig.yaml:

masterPassword: your_password
defaultNetwork: mainnet
accounts:
  - name: xxxxxx
    serverUrl: 127.0.0.1:10009
    lndDir: /lnd

and Accessing thunderHub via http://localhost:3000 over a vpn

**Comment by LucScu** [comment]
@emplexity i missed --network host thx you and @bota87 
@apotdevin do you think could be useful add this configuration to the docs?
