### ISSUE TITLE
mempool_url from environment file not used

### ISSUE THREAD

**Issue by Sroose** [apotdevin/thunderhub#376]
Thunderhub does not take into account the `MEMPOOL_URL` parameter in your .env(.local) file.
It will always take the one coded in [appUrls.ts](https://github.com/apotdevin/thunderhub/blob/master/src/client/src/utils/appUrls.ts)

I suspect the .env is not yet read in at the time the `appUrls` const is exported

* Version of ThunderHub: latest 

**To Reproduce**
1. try to configure mempool_url in .env.local to something custom
2. open the chain tab and click on a tx link

**Expected behavior**
It should use the custom url

**Actual behavior**
It uses the hardcoded default

**Additional context**
When you print the mempoolUrl to console it is correct. This leads me to believe it's a race issue where the export is done too soon

**Comment by apotdevin** [comment]
Hey! Should be fixed in https://github.com/apotdevin/thunderhub/commit/80ff6bfb25b3a161bbb65e9a4d359b50ee2f8cd5 if you want to test it out

**Comment by Sroose** [comment]
solved ✔️ thank you
