### ISSUE TITLE
Scores page link to BOSScore help broken

### ISSUE THREAD

**Issue by jeremycadams** [apotdevin/thunderhub#386]
On current Umbrel (0.4.11) when node is not represented in the list, a link is given to more info about BOSScores: "This node is not in the BOS list. Read more about these scores here." <https://openoms.gitbook.io/lightning-node-management/bosscore>. This is a dead link.

The new link should go to <https://www.lightningnode.info/advanced-tools/bosscore>

**Comment by apotdevin** [comment]
This view is now deprecated in the later versions of TH
