### ISSUE TITLE
Docker image v0.13.5 Error: spawn nest ENOENT

### ISSUE THREAD

**Issue by aphex3k** [apotdevin/thunderhub#393]
**Describe the problem/bug**
Updating docker image from v0.12.31 to v0.13.5 fails. The docker image throws an error while starting.

**Screenshots/Links**

- https://github.com/getumbrel/umbrel/pull/1213

```bash
$ docker logs thunderhub_web_1
```
```node
> thunderhub@0.13.5 start /app
> cross-env NODE_ENV=production nest start

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn nest ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn nest',
  path: 'nest',
  spawnargs: [ 'start' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thunderhub@0.13.5 start: `cross-env NODE_ENV=production nest start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thunderhub@0.13.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
**Additional context**

- This is running in Umbrel context. The PR linked above contains the [docker-compose file](https://github.com/getumbrel/umbrel/pull/1213/files#diff-8db4d675c5d6d1d2bf4eb883b947a0958a3c8ea62efd5a31ed069e6cf1c2cfac) used to start the container
- docker-compose version 1.29.2, build 5becea4c
- Linux <redacted hostname> 4.19.0-18-amd64 # 1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by aphex3k** [comment]
@apotdevin I updated the issue from v0.13.1 to v0.13.2 and while the error seems different now it is probably a similar issue.

**Comment by aphex3k** [comment]
> @apotdevin I updated the issue from v0.13.1 to v0.13.2 and while the error seems different now it is probably a similar issue.

v0.13.2 to v0.13.5 all exercise the same issue as mentioned above.

**Comment by apotdevin** [comment]
Hey, let me check. Might have messed something up with the arm image

**Comment by aphex3k** [comment]
> Hey, let me check. Might have messed something up with the arm image

I run umbrel OS on x86_64 so this is not limited to arm

**Comment by apotdevin** [comment]
Ah I see. Tested on a raspberry pi and confirmed that's working at least. Tested on an amd64 machine as well and it's working fine. Anything else I can test to try to reproduce?

**Comment by aphex3k** [comment]
> Ah I see. Tested on a raspberry pi and confirmed that's working at least. Tested on an amd64 machine as well and it's working fine. Anything else I can test to try to reproduce?

Are you starting thunderhub using npm or do you launch the docker container?

**Comment by apotdevin** [comment]
Docker container

**Comment by aphex3k** [comment]
It looks like there was a change from 0.12.31 to 0.13.0 regarding how the app starts, and then another change from 0.13.1 to 0.13.2. (0.13.1 was missing cross-env?). 

```
> thunderhub@0.13.5 start /app
> cross-env NODE_ENV=production nest start

events.js:292
      throw er; // Unhandled 'error' event
      ^
```

I'm not sure where event.js belongs to, whether it it is a node component or belongs to the thunderhub application but maybe you can check why it might throw an error at line 292?

**Comment by aphex3k** [comment]
When I run `docker run --rm apotdevin/thunderhub:v0.13.5` it seems to launch successfully. Something in the docker-compose file in the residual configuration from 0.12.31 makes it not launch correctly. I'm trying to narrow it down further.

**Comment by aphex3k** [comment]
Running `docker run --rm --user 1000:1000 apotdevin/thunderhub:v0.13.5` will crash at launch with a permission issue
```
(node:18) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open 'schema.gql'
```

**Comment by aphex3k** [comment]
This is the log file npm writes
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thunderhub@0.13.5~prestart: thunderhub@0.13.5
6 info lifecycle thunderhub@0.13.5~start: thunderhub@0.13.5
7 verbose lifecycle thunderhub@0.13.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle thunderhub@0.13.5~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle thunderhub@0.13.5~start: CWD: /app
10 silly lifecycle thunderhub@0.13.5~start: Args: [ '-c', 'cross-env NODE_ENV=production nest start' ]
11 silly lifecycle thunderhub@0.13.5~start: Returned: code: 1  signal: null
12 info lifecycle thunderhub@0.13.5~start: Failed to exec start script
13 verbose stack Error: thunderhub@0.13.5 start: `cross-env NODE_ENV=production nest start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid thunderhub@0.13.5
15 verbose cwd /app
16 verbose Linux 4.19.0-18-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.15.5
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error thunderhub@0.13.5 start: `cross-env NODE_ENV=production nest start`
22 error Exit status 1
23 error Failed at the thunderhub@0.13.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aphex3k** [comment]
I believe the custom entrypoint in umbrel is the culprit.

**Comment by aphex3k** [comment]
I figured it out. This is not a thunderhub issue!

**Comment by apotdevin** [comment]
Awesome! Thanks for investigating. Any clue what it was?

**Comment by aphex3k** [comment]
Yes @apotdevin, @kroese you are correct. It was not a thunderhub issue but the custom entrypoint script that umbrel provided to launch thunderhub needed updating. That fixed it on my machine at least.
