### ISSUE TITLE
Channel view fails with Int cannot represent non 32-bit signed integer value

### ISSUE THREAD

**Issue by gonzaloaune** [apotdevin/thunderhub#40]
**Describe the problem/bug**
When having many channels, the following views failed to load:

* Channels
* Balance
* Fees

**Your environment**
* Version of ThunderHub: 0.6.0 (happening with 0.5.5 originally)
* Deployment method:  Docker
* Other relevant environment details: Running in an Ubuntu 18.04 LTS x86_64

**To Reproduce**
1. Go to either Channels or Balance
2. See error

**Expected behavior**
Display the channels or balance information.

**Actual behavior**
The screen shows nothing and an error pops up.

**Screenshots/Links**
<img width="322" alt="Screenshot 2020-05-20 at 10 47 39" src="https://user-images.githubusercontent.com/219565/82433395-48280200-9a89-11ea-9fb1-4e43820d8cd9.png">

**Additional context**
The problem comes from time_online & time_offline being stored as Int instead of BigInt.

<img width="667" alt="Screenshot 2020-05-20 at 19 09 15" src="https://user-images.githubusercontent.com/219565/82481599-762f3580-9acd-11ea-9ee7-3506c06a183d.png">

**Comment by apotdevin** [comment]
Closed with https://github.com/apotdevin/thunderhub/commit/66a35fed92a1a492cafe1b5f77b2f13dfa655d5d

**Comment by RandyMcMillan** [comment]
![Screen Shot 2021-10-06 at 10 57 12 PM](https://user-images.githubusercontent.com/152159/136313437-4899cbd4-c5ea-4470-a188-ec167b69fd47.png)

![Screen Shot 2021-10-06 at 11 00 34 PM](https://user-images.githubusercontent.com/152159/136313490-2bf58a70-25ef-4a56-b690-8ca114ce4ba4.png)

**Comment by RandyMcMillan** [comment]
Using signet - when the bitcoin wallet contains a large amount of satoshis.
