### ISSUE TITLE
update channels fees directly in the dashboard

### ISSUE THREAD

**Issue by imirkth** [apotdevin/thunderhub#403]
**Is your feature request related to a problem? Please describe.**
on version 12, in the dashboard, we could just click on a channel and update the fees. now we have to click on a button, that takes us to a different screen, then we update the fees, then we have to click again to access the dashboard and start again.

**Describe the solution you'd like**
i would prefer to still have the pop up to be able to change the fees.

Thanks a lot!

**Comment by apotdevin** [comment]
Hi! Thanks for the request, you can now do this in version 0.13.7
