### ISSUE TITLE
LNMarkets login button no longer works

### ISSUE THREAD

**Issue by premghinde** [apotdevin/thunderhub#404]
**Describe the problem/bug**
Latest update has broken the ability to log into linked LNMarkets account.

**Your environment**
* Version of ThunderHub: 0.13.1
* Deployment method: BTCPay Server v1.4.3.0
* Other relevant environment details: None

**To Reproduce**
1. Go to Home
2. Click on LnMarkets Login
4. See error "Cannot read property 'entropyToMnemonic' of undefined"

**Expected behavior**
LnMarkets account is accessible

**Actual behavior**
Only error bubble is shown

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/1353207/153026096-c1280b91-5ab7-43e8-b75e-645a9664cc81.png)

**Comment by apotdevin** [comment]
Hi! Please update to the latest version. This should be fixed
