### ISSUE TITLE
LN Markets Login throws a "ExpectedLndWithSupportForDeriveSharedKey"

### ISSUE THREAD

**Issue by TrezorHannes** [apotdevin/thunderhub#405]
**Describe the problem/bug**
Similar topic, but presumably different reason to #404.
Recently migrated node and LND from docker to baremetal, and I -think- my LND environment is not setup to share a key for LN Market Login via Thunderhub Start page. When I click on it, I get a warning banner saying "ExpectedLndWithSupportForDeriveSharedKey"
![image](https://user-images.githubusercontent.com/35168804/153083338-6b660f2b-c5c1-40a9-9067-c3d298d2a633.png)

I've searched for more details on Shared Key environment for LND, but this is a little over my head. Hopefully someone can share some pointer if there is either something in Thunderhub .env.local or in LND which I need to adjust for allowing to login via TH directly

**Your environment**
* Version of ThunderHub: 0.13.6
* Deployment method: npm install && npm run build and running via systemctl
* Other relevant environment details:
lnd version 0.14.2-beta commit=v0.14.2-beta
compiled binary via 
`make && make install tags="autopilotrpc chainrpc invoicesrpc routerrpc signrpc walletrpc watchtowerrpc wtclientrpc"

**To Reproduce**
1. Go to 'Homepage'
2. Click on 'LN Market Login'

**Expected behavior**
Open new window in LN Markets, like in my previous setup

**Actual behavior**
The error banner on the top right (see screenshot in description) with no further action

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/35168804/153083338-6b660f2b-c5c1-40a9-9067-c3d298d2a633.png)

Much appreciate any pointers, where can I dig in a little further. Thank you!

**Comment by TrezorHannes** [comment]
Adding some additional context, since it might be related to the Node version?
```
node --version v17.4.0
npm --version 8.3.1
```

Clicking on LN Markets login creates the following Log Entries:
```
Feb 11 11:55:22 debian-nuc npm[657012]:   context: 'ExceptionsHandler',
Feb 11 11:55:22 debian-nuc npm[657012]:   stack: [
Feb 11 11:55:22 debian-nuc npm[657012]:     'Error: error:0308010C:digital envelope routines::unsupported\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at new Hash (node:internal/crypto/hash:67:19)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at createHash (node:crypto:135:10)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at Object.hash160 (/home/web/thunderhub/node_modules/bip32/src/crypto.js:15:16)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at BIP32.get identifier [as identifier] (/home/web/thunderhub/node_modules/bip32/src/bip32.js:67:27)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at BIP32.get fingerprint [as fingerprint] (/home/web/thunderhub/node_modules/bip32/src/bip32.js:70:25)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at BIP32.derive (/home/web/thunderhub/node_modules/bip32/src/bip32.js:153:92)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at /home/web/thunderhub/node_modules/bip32/src/bip32.js:188:35\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at Array.reduce (<anonymous>)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at BIP32.derivePath (/home/web/thunderhub/node_modules/bip32/src/bip32.js:180:30)\n' +
Feb 11 11:55:22 debian-nuc npm[657012]:       '    at LnUrlService.lnAuthUrlGenerator (/home/web/thunderhub/src/server/modules/api/lnurl/lnurl.service.ts:62:26)'
Feb 11 11:55:22 debian-nuc npm[657012]:   ],
Feb 11 11:55:22 debian-nuc npm[657012]:   level: 'error',
Feb 11 11:55:22 debian-nuc npm[657012]:   message: 'error:0308010C:digital envelope routines::unsupported',
Feb 11 11:55:22 debian-nuc npm[657012]:   timestamp: '2022-02-11T10:55:22.111Z'
```
Any pointers would be appreciated - thanks!

**Comment by apotdevin** [comment]
Hey! Yeah, can you test with a lower node version? For example the docker images use 14.15

gRPC sometimes has issues with different node versions which might be the reason for this error
