### ISSUE TITLE
Starting with error: --insecure-http-parser is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by openoms** [apotdevin/thunderhub#41]
**Describe the problem/bug**
`--insecure-http-parser is not allowed in NODE_OPTIONS` error when attempting to start ThunderHub

**Your environment**
* Version of ThunderHub: 0.6.0 
* Deployment method: https://gist.github.com/openoms/8ba963915c786ce01892f2c9fa2707bc
* Other relevant environment details: RaspiBlitz latest (v1.5+)

**To Reproduce**
Same out come when installing with yarn or npm.

**Expected behavior**
start ThunderHub server

**Actual behavior**
```
$ npm run start -- -p 3001

> thunderhub@0.6.0 start /home/thunderhub/thunderhub
> cross-env NODE_OPTIONS='--insecure-http-parser' next start "-p" "3001"

node: --insecure-http-parser is not allowed in NODE_OPTIONS
npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! thunderhub@0.6.0 start: `cross-env NODE_OPTIONS='--insecure-http-parser' next start "-p" "3001"`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the thunderhub@0.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thunderhub/.npm/_logs/2020-05-20T10_34_13_974Z-debug.log
```
**Screenshots/Links**
![image](https://user-images.githubusercontent.com/43343391/82436678-1ebda500-9a8e-11ea-9d61-e9dd2ee42556.png)

**Comment by apotdevin** [comment]
Hey, currently have to pass in `--insecure-http-parser` to get the HodlHodl integration working but it's a command specific to node versions 12.16 and up.

You can also run `npm run start:compatible -- -p 3001` to get it working with previous versions but the HodlHodl integration wont work. 

Which node version is installed on the Raspiblitz? Could add a compatible command to have it working on earlier versions and keeping Hodl integration working

**Comment by openoms** [comment]
Right, it is the Node version.
we have Node.js v12.14.1 currently, but can update for the next release with ThunderHub.

**Comment by apotdevin** [comment]
Would be great, if you have some other dependency that needs this version let me know and I'll add a compatible command for it. Shouldn't take long :)

**Comment by openoms** [comment]
with the suggested command I get:
```
$ npm run start:compatible — -p 3001

> thunderhub@0.6.0 start:compatible /home/thunderhub/thunderhub
> next start "—" "3001"

Error: Could not find a valid build in the '/home/thunderhub/thunderhub/—/.next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (/home/thunderhub/thunderhub/node_modules/next/dist/next-server/server/next-server.js:974:23)
    at new Server (/home/thunderhub/thunderhub/node_modules/next/dist/next-server/server/next-server.js:64:29)
    at createServer (/home/thunderhub/thunderhub/node_modules/next/dist/server/next.js:2:328)
    at start (/home/thunderhub/thunderhub/node_modules/next/dist/server/lib/start-server.js:1:323)
    at nextStart (/home/thunderhub/thunderhub/node_modules/next/dist/cli/next-start.js:20:125)
    at /home/thunderhub/thunderhub/node_modules/next/dist/bin/next:28:339
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thunderhub@0.6.0 start:compatible: `next start "—" "3001"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thunderhub@0.6.0 start:compatible script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thunderhub/.npm/_logs/2020-05-20T11_11_55_593Z-debug.log
```

**Comment by openoms** [comment]
Yes, probably just easiest to update NodeJS. 
we are using that for RTL and Balance of Satoshis, both should run with the latest.

**Comment by apotdevin** [comment]
Looks like the command is being parsed different. It shows `next start "—" "3001"` but should be `next start "-p" "3001"`. Maybe the command is different on raspberry, will check

**Comment by openoms** [comment]
The above is actually on an Odroid SBC running Armbian Buster (based on Debian Buster same as the Raspbian on the RPi-s)

**Comment by apotdevin** [comment]
That's very wierd. The command should be standard for npm everywhere like this `npm run <command> [-- <args>]`

Just to double check, after `start` its two `-` correct?

**Comment by apotdevin** [comment]
Have added two more scripts for the mean time. You can now try either `npm run start:two` or `npm run start:compatible:two`. This should start the server directly on port `3001`. Let me know if it works!

**Comment by openoms** [comment]
I can confirm that   
`npm run start:compatible -- -p 3001`   
and  
`npm run start:compatible:two`  
are both working with Node version v12.4.1
