### ISSUE TITLE
Sending payments with Out Channels attribute not working

### ISSUE THREAD

**Issue by julienPhA** [apotdevin/thunderhub#421]
Hello guys,
This is about the following problem:
I want to send a lightning payment via a specific outgoing channel. At the moment I have two channels (call it A and B).
So I decided to pay with channel A and I only set  A in "Out Channels" option (Max Paths = 9). Thunderhub is clearly displaying Hop1 = A in transactions view.
If I look into the lightning view of Umbrel, I see a change of B's balance. Also RTL shows me a transaction with 4 failed HTLC (each has Hop1 = A), but the successful HTLC no. 5 has Hop1 = B.
After this I tried a transaction - same amount of sats, same fee limit - with RTL and set first outgoing channel to A. It succeeded at HTLC no. 13.
So I guess ThunderHub did not find any route with Max Paths = 9 and out channel A.
Why will this transaction not fail but bypass my out channel option?
Also why is this happening as early as HTLC no. 5?
And why does ThunderHub show me a wrong routing path (Hop1 = A) while Umbrel and RTL tell me a different one?
Last thing I want to say is, this issue **happened a few times** so far, not only specific to this single transaction.
Because of that I decided to open this issue here.

* Version of ThunderHub: 0.12.31
* Deployment method: Umbrel app store
* Other relevant environment details:
* Version of Umbrel: 0.4.15-build-0832902
* Version of LND: v0.14.2-beta
* Version of RTL: 0.12.1-beta

**To Reproduce**
1. Open more than one lightning channel
2. Send a lightning payment with Max Fee, Max Paths, Out Channels options
3. Choose only one of your channels for this payment
4. If it succeeded, compare the routing path of ThunderHub with RTL

**Expected behavior**
The transaction should fail with an error message instead of bypassing the set option out channels.

**Actual behavior**
ThunderHub shows a wrong routing path and did a transaction against my "rules".

**Screenshots**
![out going RTL](https://user-images.githubusercontent.com/62464042/158015747-bec5852c-a2e0-4742-9663-00da722c250f.png)
![out channel TH](https://user-images.githubusercontent.com/62464042/158015749-e58e68bb-2a9c-4bf8-8ead-b8b3d19f4bb8.png)

**Comment by jblachly** [comment]
Yes, I just experienced this and came to report it. I tried to route out through a peer with known low routing fees, but the entry was ignored completely in route construction.

**Comment by julienPhA** [comment]
unfortunately the latest version isn't available on umbrel so far :(
