### ISSUE TITLE
[Feature Request] Please add option to turn OFF all notification

### ISSUE THREAD

**Issue by Wired4ncer** [apotdevin/thunderhub#438]
Hello. It would be really nice to have option to turn off all notification. My Thunderhub have never ending spam of rebalances and forwarding which is making it quite hard to work with as the popup notification just keep coming.

Adding simple option in the notification settings to turn off all notification would sort the issue.

Thank you

**Comment by callebtc** [comment]
This would be extremely helpful. Bumping up this issue.

**Comment by drmartinberger** [comment]
Hi @Wired4ncer @callebtc ,

In version `0.13.10`, you can adjust notifications under general settings (icon top right):

![notify](https://user-images.githubusercontent.com/24563449/167247994-77ab2023-55bd-40fc-b6e1-f685a982ce0e.png)

Doesn't that solve your issue?

**Comment by Wired4ncer** [comment]
Well there is an option to show all forwards and auto close, but it would be great to also have option to turn off all notifications. With medium size routing node I have never stopping notifications in Thunderhub.

**Comment by apotdevin** [comment]
Latest version should now have toggles for all notification types
