### ISSUE TITLE
Can’t start Thunderhub

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [apotdevin/thunderhub#440]
**Describe the problem/bug**
I just installed Thunderhub on my Raspibolt. Until starting up the program everything went OK. But if I try to start Thunderhub I’ll get always the same error:

`}
Error: Could not find a production build in the '/home/thunderhub/thunderhub/src/client/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/home/thunderhub/thunderhub/node_modules/next/server/next-server.ts:168:15)
    at new Server (/home/thunderhub/thunderhub/node_modules/next/server/base-server.ts:293:25)
    at new NextNodeServer (/home/thunderhub/thunderhub/node_modules/next/server/next-server.ts:98:5)
    at NextServer.createServer (/home/thunderhub/thunderhub/node_modules/next/server/next.ts:124:12)
    at /home/thunderhub/thunderhub/node_modules/next/server/next.ts:140:23
{
`
**Your environment**
* Version of ThunderHub: thunderhub@0.13.10 start
* Other relevant environment details: raspibolt

Not sure but maybe I did something wrong in this part of the manual, because I’m not really sure which PW you mean with «masterPassword» and «accountpassword». What is the difference?
: 
`masterPassword: 'PASSWORD' # Default password unless defined in account
accounts:
  - name: 'RaspiBolt'
    serverUrl: '127.0.0.1:10009'
    macaroonPath: '/home/thunderhub/admin.macaroon'
    certificatePath: '/home/thunderhub/.lnd/tls.cert'
    password: 'accountpassword'
`
Thx in advance for your support.

**Comment by seth586** [comment]
Have the same problem trying to run this on FreeBSD12.3, what fixed this?
