### ISSUE TITLE
Redirect on Unauthorized has high latency (UX bug)

### ISSUE THREAD

**Issue by ProofOfKeags** [apotdevin/thunderhub#449]
**Describe the problem/bug**
If you are logged out of Thunderhub and navigate to `/`, Thunderhub will render a page indicating "you are not allowed to view this page" for about 1-2 seconds before redirecting you. This should be close to instant (<100ms).

**Your environment**
* Version of ThunderHub: 13.10
* Deployment method: Docker / EmbassyOS
* Other relevant environment details:

**To Reproduce**
1. Log out
2. navigate to `/`
3. Observe the unauthenticated page

**Expected behavior**
Immediately redirect to login page.

**Actual behavior**
"You are not allowed to view this page" for two seconds, then redirect

**Screenshots/Links**
![Screenshot from 2022-05-03 14-22-28](https://user-images.githubusercontent.com/4033651/166559664-514ccf50-e381-40da-bc4e-0e2392d7e7e2.png)

**Comment by apotdevin** [comment]
Fixed in commit 896ad1be2c50a9ac154e6dc99db6077895659235! Will get it into the next version release
