### ISSUE TITLE
Dockerhub v0.13.13 amd64 image contains v0.13.12

### ISSUE THREAD

**Issue by vilm3r** [apotdevin/thunderhub#454]
**Describe the problem/bug**
When pulling v0.13.13 from Dockerhub the wrong version of Thunderhub is provided.

**To Reproduce**
1. Pull v0.13.13 from Dockerhub on amd64 arch
2. Login to Thunderhub
3. See v0.13.12 in footer

**Expected behavior**
v0.13.13 is provided in the image.

**Actual behavior**
v0.13.12 is provided.

**Comment by dougEfresh** [comment]
The package version is incorrect for the tag 0.13.13
https://github.com/apotdevin/thunderhub/blob/v0.13.13/package.json#L3

**Comment by apotdevin** [comment]
Tag should be synced with image version in the later versions
