### ISSUE TITLE
Feature: Boltz LSP integration

### ISSUE THREAD

**Issue by peartobear** [apotdevin/thunderhub#47]
**Problem.**

Lightning power users want an easy way to on and off ramp themselves from the lightning economy in a self-custodial and trust minimized manner. 

**Solution**

[Submarine Swaps](https://medium.com/boltzhq/submarine-swaps-c509ce0fb1db) allows for just that. [Boltz](https://boltz.exchange) acts as a Lightning service provider and abstracts out the complexity that comes with integrating these swaps for frontend developers via a RESTful API. [Here](https://docs.boltz.exchange/en/latest/) is the documentation for reference. Boltz is built on the principals of privacy and open-source - some values we all share. 

**Alternative**
Loop by Lightning Labs also provides this service but requires running a daemon and have additional setup requirements for end-users.  Issue Ref: https://github.com/apotdevin/thunderhub/issues/22

**Example**
A sneak-peak of Boltz LSP integration in RTL (currently under development)

![Screenshot 2020-05-21 at 7 18 01 PM](https://user-images.githubusercontent.com/44926540/82565315-d7bbd680-9b97-11ea-8401-a72cb6709517.png)

**Additional Context**

Boltz was also first to [demo](https://twitter.com/Boltzhq/status/1262110466509115392?s=20) self custodial channel creation swap on mainnet and plans to offer that as an API feature as well - it will further make the UX of node management tools easier.

**Comment by apotdevin** [comment]
Hey! Thanks for opening the feature request. Looks like a great option to allow swaps without needing a Loop daemon running. Will keep it in mind and see when some time is available to do an initial integration

**Comment by Kixunil** [comment]
I'm also interested in this feature and I noticed boltz also have a daemon. I'm not sure how it's non-mandatory - perhaps other applications are responsible for the actions performed by it? (Possibly in library form.)

A bigger advantage for me is that they open-sourced their backend as well which is mainly useful for testing on regtest. Testing loop on regtest is currently impossible.

Anyway, having to run a separate daemon is pretty much non-issue for me personally. I already prepared the required infrastructure to make it easy.

**Comment by michael1011** [comment]
> I'm also interested in this feature and I noticed boltz also have a daemon. I'm not sure how it's non-mandatory - perhaps other applications are responsible for the actions performed by it? (Possibly in library form.)

We have two daemons right now.

- [boltz-backend](https://github.com/boltzexchange/boltz-backend): which is our backend that we run for boltz.exchange 
- [boltz-lnd](https://github.com/boltzexchange/boltz-lnd): which is really similar to the loop client daemon

But one can use Boltz without the boltz-lnd. We have a [TypeScript library](https://github.com/boltzexchange/boltz-core) that abstracts all the low level Bitcoin scripting and our REST API is (*somewhat*) well documented: https://docs.boltz.exchange/en/latest/api/

> Anyway, having to run a separate daemon is pretty much non-issue for me personally. I already prepared the required infrastructure to make it easy.

In case you mean running the backend on regtest, there are some [docs for setting up the Boltz backend on regtest](https://docs.boltz.exchange/en/latest/regtest/) but those are mostly for our regtest Docker images. Feel free to reach out to me in case you have issues setting it up!

**Comment by Kixunil** [comment]
I meant both. :) I want to integrate it into [my Debian repository](https://deb.ln-ask.me). I should be able to figure it out myself.

**Comment by apotdevin** [comment]
Boltz reverse swap is now integrated in version 0.10.3
