### ISSUE TITLE
Channels not being displayed

### ISSUE THREAD

**Issue by Whabster** [apotdevin/thunderhub#493]
When selecting the channel tab a warning comes up in the top right: expectedcommitmenttypeinchannelmessage.

**Your environment**
* Version of ThunderHub: 0.12.30
* Deployment method: LAN 
* Other relevant environment details: Brave Browser

Any help would be appreciated.

**Comment by apotdevin** [comment]
Please update your TH version. This has been fixed already

**Comment by Whabster** [comment]
Thanks. Great tool!!!
