### ISSUE TITLE
GraphQL error while sending payments

### ISSUE THREAD

**Issue by dasquantum2909** [apotdevin/thunderhub#502]
**Describe the problem/bug**
Whenever I try to send payments I am receiving graphql error

**Your environment**
* Version of ThunderHub: 0.13.18
* Deployment method: using umbrel bundled package
* Other relevant environment details: RPI4, ubuntu, umbrel lightning node

**To Reproduce**
1. Go to 'Home'
2. Click on 'send'
3. Provide invoice
4. Select the out channels
5. See error- Graphql error

**Expected behavior**
It should send the payment

**Actual behavior**
Throws graphql error
`{"graphQLErrors":[],"clientErrors":[],"networkError":{"name":"ServerError","response":{},"statusCode":400,"result":{"errors":[{"message":"Variable \"$out\" got invalid value null at \"out[0]\"; Expected non-nullable type \"String!\" not to be null.","locations":[{"line":1,"column":52}],"extensions":{"code":"BAD_USER_INPUT"}}]}},"message":"Response not successful: Received status code 400"}`

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/119115808/209926776-6022e49b-9665-40f7-bc28-80b79c33dbea.png">

**Additional context**

**Comment by aphex3k** [comment]
This is actually a network/server error instead of GraphQL if you look at the error message more closely. I described the same behavior in #508

**Comment by apotdevin** [comment]
Fixed with https://github.com/apotdevin/thunderhub/pull/531
