### ISSUE TITLE
Selecting an outgoing peer when paying lightning invoice fails with lnd v0.15.5

### ISSUE THREAD

**Issue by aphex3k** [apotdevin/thunderhub#508]
**Describe the problem/bug**
Since updating to v0.15.5 of lnd when paying a lightning invoice that has an outgoing peer selected, the payment fails with an error. Paying lightning invoices without peer selection is successful. It doesn't matter how many outgoing peers are selected and what their channel liquidity state is, as soon as the first outgoing peer is selected, the payment fails.

```
{
  "graphQLErrors": [],
  "clientErrors": [],
  "networkError": {
    "name": "ServerError",
    "response": {},
    "statusCode": 400,
    "result": {
      "errors": [
        {
          "message": "Variable \"$out\" got invalid value null at \"out[0]\"; Expected non-nullable type \"String!\" not to be null.",
          "locations": [
            {
              "line": 1,
              "column": 52
            }
          ],
          "extensions": {
            "code": "BAD_USER_INPUT"
          }
        }
      ]
    }
  },
  "message": "Response not successful: Received status code 400"
}
```
(pretty print formatting added by me)

**Your environment**
* Version of ThunderHub: v0.13.18
* Deployment method: docker
* Other relevant environment details: lnd-v0.15.5-beta

**To Reproduce**
1. Acquire a lightning invoice
2. Paste lightning invoice in ThunderHub 
   - it is irrelevant which screen is used to trigger the payment (home/dashboard widget/...) 
   - the invoice will decode correctly
3. select at least one Out Channel
4. Click Pay

**Expected behavior**
Previously the payment would succeed taking into account all the user selections made on the Payment UI.

**Actual behavior**
The payment will fail with the error pasted above and shown in the screenshot below.

**Screenshots/Links**
<img width="341" alt="Screenshot 2023-01-11 at 9 04 04 PM" src="https://user-images.githubusercontent.com/433270/211981890-51d5a6b8-80b8-4164-b746-474c12373d4a.png">

**Additional context**
I'm not sure if this stopped working in v0.15.5 exactly or earlier but this feature used to work as intended before. I used it previously to specifically pay my RoboSats invoices forcing it through the channel my node has with RoboSats as opposed to route it anywhere else.

**Comment by aphex3k** [comment]
Possibly a duplicate of #502

**Comment by apotdevin** [comment]
Fixed with https://github.com/apotdevin/thunderhub/pull/531
