### ISSUE TITLE
Changes to Channel View

### ISSUE THREAD

**Issue by apotdevin** [apotdevin/thunderhub#55]
**Is your feature request related to a problem? Please describe.**
I want more options for sorting and viewing in the Channels view and easier channel finding/viewing in the balancing view

**Describe the solution you'd like**
- Sort by channel size
- Sort by partner node name
- See fees without expanding the channel

**Comment by Jestopher-BTC** [comment]
- Sort by max payment out
- Sort by historical routed payment volume outbound

**Comment by apotdevin** [comment]
Closed by 7b970e549473f31bfc9c879e0ca6733e60cc02fb

Continues on https://github.com/apotdevin/thunderhub/issues/73
