### ISSUE TITLE
Balancing and Channel view integration

### ISSUE THREAD

**Issue by apotdevin** [apotdevin/thunderhub#56]
**Is your feature request related to a problem? Please describe.**
Currently channel view and balancing view are not integrated which makes for a bad UX

**Describe the solution you'd like**
- Better integration of the balance and channel view for a more seamless experience

**Comment by Swissnode** [comment]
Consider drag-and-drop if that's at all possible. Drag the outgoing channel onto the incoming one to start a rebalancing attempt :)

**Comment by Swissnode** [comment]
Alternatively, in the "channels" screen, add a button to each channel "add to outgoing" / "add to incoming" to set the channels being rebalanced

**Comment by apotdevin** [comment]
An initial integration can be tested on version 0.8.5. Closed by fdda98f1cbc8077dbb60df67630a235741dce214
