### ISSUE TITLE
Amboss icon doesn't show on Home page in Quick Action section

### ISSUE THREAD

**Issue by MButcho** [apotdevin/thunderhub#566]
**Describe the problem/bug**
Amboss icon doesn't show on home page in Quick Actions
Sep 09 12:53:30 machine npm[433626]: upstream image response failed for /assets/amboss_icon.png TypeError: fetch failed
Sep 09 12:53:30 machine npm[433626]:     at Object.fetch (node:internal/deps/undici/undici:11576:11)
Sep 09 12:53:30 machine npm[433626]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 09 12:53:30 machine npm[433626]:     at async invokeRequest (/thunderhub/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
Sep 09 12:53:30 machine npm[433626]:     at async /thunderhub/node_modules/next/dist/server/next-server.js:359:35
Sep 09 12:53:30 machine npm[433626]:     at async imageOptimizer (/thunderhub/node_modules/next/dist/server/image-optimizer.js:537:13)
Sep 09 12:53:30 machine npm[433626]:     at async cacheEntry.imageResponseCache.get.incrementalCache (/thunderhub/node_modules/next/dist/server/next-server.js:598:60)
Sep 09 12:53:30 machine npm[433626]:     at async /thunderhub/node_modules/next/dist/server/response-cache/index.js:99:36 {
Sep 09 12:53:30 machine npm[433626]:   cause: Error: connect ECONNREFUSED 127.0.0.1:3000
Sep 09 12:53:30 machine npm[433626]:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
Sep 09 12:53:30 machine npm[433626]:     errno: -111,
Sep 09 12:53:30 machine npm[433626]:     code: 'ECONNREFUSED',
Sep 09 12:53:30 machine npm[433626]:     syscall: 'connect',
Sep 09 12:53:30 machine npm[433626]:     address: '127.0.0.1',
Sep 09 12:53:30 machine npm[433626]:     port: 3000
Sep 09 12:53:30 machine npm[433626]:   }
Sep 09 12:53:30 machine npm[433626]: }

**Your environment**
* Version of ThunderHub: 0.13.22
* Deployment method: npm start
* Other relevant environment details: Ubuntu 22.04, lnd version 0.16.4-beta commit=v0.16.4-beta, running on port 3010

**To Reproduce**
1. Click Home

**Expected behavior**
N/A

**Actual behavior**
Home page doesn't display amboss icon

**Additional context**
When I edit /thunderhub/node_modules/next/dist/server/next-server.js and change line 359:
_**From**_
const invokeRes = await (0, invokerequest.invokeRequest)(http://${this.fetchHostname || "localhost"}:**${this.port}**${newReq.url || ""}, {
_**To**_
const invokeRes = await (0, invokerequest.invokeRequest)(http://${this.fetchHostname || "localhost"}:**3010**${newReq.url || ""}, {
icon is showing just fine and no error in log

**Comment by ssurfertuga** [comment]
I have the same problem here after upgrading to 0.13.23

**Comment by MButcho** [comment]
Was fixed by latest version
