### ISSUE TITLE
FullChannelDetailsNotFound on Forwarding Page

### ISSUE THREAD

**Issue by MSauce** [apotdevin/thunderhub#57]
**Describe the problem/bug**
Getting 404 error "FullChannelDetailsNotFound" when trying to load the forwarding tab. I am using the latest rc for LND (lnd v0.10.1-beta.rc3) and didn't start seeing this error until after I made a loopd transaction on this node. 

**Your environment**
* Version of ThunderHub: 0.6.0
* Deployment method: Docker

**To Reproduce**
1. Log in to node
2. Click on Forwarding

**Expected behavior**
I expect the forwarding page to load. 

**Actual behavior**
I get "error [THUB]: Error getting forwards: [ 404, 'FullChannelDetailsNotFound', [length]: 2 ]" in my logs and the forwarding tab does not load. 

Additional context: I'm also getting Unexpected error value: [404, "NodeIsUnknown"] when I try to load the "Closed" tab of the Channels tab. 

<img width="974" alt="Screen Shot 2020-06-02 at 12 36 06 PM" src="https://user-images.githubusercontent.com/5844989/83545793-b5965280-a4cd-11ea-806b-b323ed796b50.png">

**Comment by apotdevin** [comment]
Hey! Thanks for the issue. I believe I found the problem. When the one of the two nodes that where involved in the forward are not found it fails to return a result. Same with the closed channels when it doesn't find the partner node.

Will work on the fix.

**Comment by MSauce** [comment]
Cheers - let me know if theres is anything I can do to help on my end.

**Comment by MSauce** [comment]
Great work! thanks. Could you push 0.7.0 to dockerhub?

**Comment by apotdevin** [comment]
On it :)

**Comment by apotdevin** [comment]
Docker image is available for version 0.7.1

**Comment by MSauce** [comment]
Thank you very much! I'll let you know if I have more issues.
