### ISSUE TITLE
Node version update needs to be mentioned.

### ISSUE THREAD

**Issue by mutatrum** [apotdevin/thunderhub#588]
It seems v0.13.24 has bumped up the Node version requirement to 18. If this is correct, this is not mentioned in the release notes, and https://docs.thunderhub.io/setup still mentions Node 14.

**Comment by mutatrum** [comment]
As discussed on Telegram: it seems to build ok with Node 20.

**Comment by twofaktor** [comment]
Already modified: https://github.com/apotdevin/thunderhub-docs/pull/7
https://docs.thunderhub.io/setup
