### ISSUE TITLE
Centre local/remote balance on channels screen

### ISSUE THREAD

**Issue by Swissnode** [apotdevin/thunderhub#60]
**Is your feature request related to a problem? Please describe.**
Instead of showing remote and local underneath each other, put them besides each other and align them

**Describe the solution you'd like**
The current bar height could be doubled. I would also put a 3-significant figure shorthand of the amount within the bars (see diagram). Anything with 7 digits becomes "M" for millions, anything with 4 digits becomes "k". Do not show more than 3 numbers as the user is not interested in more. Include the exact amount in the detail dropdown.

This view would HAVE to be proportional...

**Describe alternatives you've considered**
Use the colours that you have in the fee stats screen (red to green) to colour the bars instead of just green and blue. In this way the colour is meaningful

A second alternative would be to included the "balancedness" of the channel as a small number in the top right of the panel holding the channel...

**Provide examples**
This is what it used to look like:

![image](https://user-images.githubusercontent.com/54310929/83937430-cfd17880-a7cc-11ea-98e0-1079cdcad127.png)

This is my suggestion:

![image](https://user-images.githubusercontent.com/54310929/83937435-d8c24a00-a7cc-11ea-988d-d5580916de2c.png)

**Additional context**
N/A

**Comment by Swissnode** [comment]
For the second alternative where I suggest putting the balancedness, i also suggest making a second version of this, and that is to put an amount in sats of how unbalanced it is instead... This might be more useful for node owners...

**Comment by apotdevin** [comment]
Closed by 7b970e549473f31bfc9c879e0ca6733e60cc02fb

Continues on https://github.com/apotdevin/thunderhub/issues/73
