### ISSUE TITLE
Can not access channels page

### ISSUE THREAD

**Issue by MrManPew** [apotdevin/thunderhub#64]
**Screenshots/Links**
![image](https://user-images.githubusercontent.com/35897350/83949906-5323b600-a82f-11ea-95c7-a3685cce8d7a.png)

**Your environment**
```
lnd version 0.10.1
thunderhub: just git pulled latest version
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux```

**Comment by apotdevin** [comment]
Hi! Thanks for catching the bug :) This is fixed with version 0.7.3 (287762cbe49667331a67f943954aa090d3d549fe)
