### ISSUE TITLE
Failed to construct `URL` when starting ThunderHub

### ISSUE THREAD

**Issue by andrerfneves** [apotdevin/thunderhub#74]
Thanks for this tool. Wanted to try it out for some of our nodes, and running into an issue.

**Describe the problem/bug**
Trying to set up ThunderHub. I have the account settings correctly placed under accounts.yaml and linked on the .env.local.

**Your environment**
* Version of ThunderHub: latest master
* Deployment method: `npm`
* Other relevant environment details: node v13.14

**Expected behavior**
It should load ThunderHub page.

**Actual behavior**
It flashes the ThunderHub screen for a split second, and then it goes white, and shows a looping error shown below where URL cannot be found. What is that URL? I have `127.0.0.1:10009` as the URL for the server account.

**Screenshots/Links**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2574011/85803756-47385f00-b71e-11ea-9dfe-90263a82acf8.png">

**Comment by apotdevin** [comment]
Hey! Thanks for the bug report. I can't reproduce this locally on that node version. Does this happen as soon as you open the webpage of after doing some action? Which env fields are you filling in? Did you use the docker image? Which thunderhub version is it?

**Comment by apotdevin** [comment]
Could you also try running with `npm run dev` and check if the error changes?

**Comment by andrerfneves** [comment]
Thanks for the response @apotdevin. This is what I see when I run `npm run dev`.
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/2574011/85865485-54942e80-b79c-11ea-9d64-a1f65d2468f6.png">

**Comment by apotdevin** [comment]
Strange error 🤔 Which environment variables are you filling in the `.env.local` file?

**Comment by andrerfneves** [comment]
```
# -----------
# Server Configs
# -----------
LOG_LEVEL = 'info'
HODL_KEY = ''
BASE_PATH = '/'

# -----------
# Interface Configs
# -----------
THEME = 'dark'
CURRENCY = 'sat'

# -----------
# Privacy Configs
# -----------
FETCH_PRICES = true
FETCH_FEES = true
HODL_HODL = false
DISABLE_LINKS = false
NO_CLIENT_ACCOUNTS = false
NO_VERSION_CHECK = false

# ---------
# Accounts
# ---------
ACCOUNT_CONFIG_PATH='/thunderhub/accounts.yaml'
```

**Comment by apotdevin** [comment]
Try commenting out or removing the `BASE_PATH` config

**Comment by andrerfneves** [comment]
That did it. Thanks @apotdevin. Looking forward to using ThunderHub.

**Comment by apotdevin** [comment]
Awesome 🤟 still this shouldnt throw an error, will fix it. Thanks for finding the bug!
