### ISSUE TITLE
add tooltip for channel status

### ISSUE THREAD

**Issue by MrManPew** [apotdevin/thunderhub#80]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/35897350/87218248-9d7de280-c359-11ea-983d-0bfba4ce3fee.png)

It would be nice if you can add a tooltip for the channel status (the red/green point) so when the cursor over those little points it will state, channel off/on or whatever other information. 

Thanks

**Comment by apotdevin** [comment]
Closed by 3a52b00e89f22226512ed59fe40b824548fe2e0a
