### ISSUE TITLE
Change node icon color?

### ISSUE THREAD

**Issue by MrManPew** [apotdevin/thunderhub#84]
![image](https://user-images.githubusercontent.com/35897350/87218422-3103e300-c35b-11ea-9921-5a6caa9df1ad.png)

There is no tooltip for the little red icon. If the icon has not meaning, it might be better to change the color to green? as red usually means that there is a problem.

**Comment by apotdevin** [comment]
Will change it 👍

**Comment by apotdevin** [comment]
Closed by 6be165c79cf6ab1e9a4455b0158e860f3d809960
