### ISSUE TITLE
Allow bar colouring with dual texts in channel screen

### ISSUE THREAD

**Issue by Swissnode** [apotdevin/thunderhub#87]
it would be great if the channel screen could be updated by allowing an additional option "fee rate colouring"

In this mode the bars would not be coloured blue and green for local/remote, but would be graded based on the local/remote fee rate that is in effect.

red would be maximum (about 4000 ppm) and green would be minimum (1) with yellow being a mid value (2000). any other ppm value would scale the colour accordingly

in order to be able to get more detail about every fee rate I suggest an additional setting (radio button) "indicator" or "values shown". this would default to e.g. "channel balance" (2.1M for example) but could be set to "fee rate" (e.g. 400)

**Comment by apotdevin** [comment]
You can now view fee rates with the `Sub Bar` option in the settings :)
