### ISSUE TITLE
Warn when node is using unsafe cltv_expiry_delta value (<18)

### ISSUE THREAD

**Issue by MrManPew** [apotdevin/thunderhub#88]
**Is your feature request related to a problem? Please describe.**
See details here:
https://github.com/lightningnetwork/lightning-rfc/issues/789
and here:
https://twitter.com/realtbast/status/1283298246983659520

I think it would be very efficient to the network if ThunderHub will show a warning when the node has channels with cltv_expiry_delta lower than the recommended value (there are more than 7k such channels on mainnet)

**Describe the solution you'd like**
I assume some warning that can be disabled in the settings.

**Comment by apotdevin** [comment]
In the details page if the channel has a lower than recommended CLTV it shows a small warning that you should increase it. Is this what you refer to?

**Comment by MrManPew** [comment]
Amazing! I did not know that.

Not sure how unsecured it is to use a low CLTV (@t-bast?) but maybe you should also add a global warning:
![image](https://user-images.githubusercontent.com/35897350/87688517-bc340d00-c78f-11ea-9607-aeb7c6ab2817.png)

Thanks!

**Comment by apotdevin** [comment]
Will look into it, if it makes sense to have a global notification or maybe a bigger notification on the details page

PS: if you go to settings > privacy card > values > hide you can hide all number values on ThunderHub 😉🙈

**Comment by t-bast** [comment]
Using a low `cltv_expiry_delta` is really asking for trouble (it means you're confident that in case of close, you're able to get many transactions confirmed very quickly - and when on-chain fees spike, you're screwed).

Nodes won't be penalized much in path-finding for using a high enough `cltv_expiry_delta`, so they should strongly consider it!

**Comment by apotdevin** [comment]
@t-bast thub will show an error if the CLTV is below 14 and a warning if it's below 24, what do you think about these defaults?

**Comment by t-bast** [comment]
@apotdevin great, thanks! Could you bump those values to error below 18 and warning below 34, to match the [values in the spec](https://github.com/lightningnetwork/lightning-rfc/pull/785)?

Ideally users will read some node operator guide at some point as well (at least if they plan on putting non-negligible amounts) and those guides should explain the trade-offs in details.

**Comment by apotdevin** [comment]
For sure, changed in c05f02ac9cb80b1d157508a694a70dc576758de7

Thanks!
