### ISSUE TITLE
Network-agnostic macaroon configuration

### ISSUE THREAD

**Issue by torkelrogstad** [apotdevin/thunderhub#90]
Right now we have to pass in the full path to the macaroon file read by Thunderhub. Would it be an idea to allow the user to specify the path in a network-agnostic way? 

Consider this: 

Thunderhub accepts environment variables (or config file keys) `BITCOIN_NETWORK` and `LND_DIR`. `BITCOIN_NETWORK` defaults to `mainnet`. 

1. `LND_DIR=/foo`: Thunderhub searches for `tls.cert` at `/foo/tls.cert` and the macaroon at `/foo/data/chain/bitcoin/mainnet/admin.macaroon`
2. `LND_DIR=/foo`, `BITCOIN_NETWORK=testnet`: Thunderhub searches for `tls.cert` at `/foo/tls.cert`, and the macaroon file at `/foo/data/chain/bitcoin/testnet/admin.macaroon`. 

If either the macaroon path is set or the tls path is set, these override the above. If the LND directory is not set, then the macaroon and cert paths must be set, but they can be omitted if the directory is specified.

This would allow users to switch between testnet, mainnet and regtest without changing multiple parts of their configuration file.

**Comment by apotdevin** [comment]
Interesting, it could make the setup easier in some cases but users could also create multiple accounts in the yaml file and switch between them without needing to change the config file.

Still think it could be a nice approach with these default paths, if you want to open a pr for this, your are more than welcome :)

**Comment by torkelrogstad** [comment]
This is fixed by #92
