### ISSUE TITLE
Enable Strict in tsconfig

### ISSUE THREAD

**Issue by torkelrogstad** [apotdevin/thunderhub#95]
I noticed that `strict` is turned off in the projects `tsconfig.json`. This really limits how useful TypeScript can be. Have you considered enabling this option? I tried it out, and as expected, got a ton of compiler failures. A great deal of them seemed to be related to the GraphQL queries. Wouldn't it be better to write the queries with non-nullable fields, instead of ignoring the problems? I'd be happy to help you out to squash compiler errors after enabling strict. 

BTW, the bug I fixed in #94 wouldn't have happened in the first place with strict mode enabled 😉

**Comment by apotdevin** [comment]
Yes! I have been looking into enabling `strictNullCheck` for a while which I shamefully forgot to enable at the beginning of the project 🤦‍♂️ (Not happening again!)

Let me have a look at the status of it and maybe we can fix this quicker between the two of us

**Comment by torkelrogstad** [comment]
It happens to the best of us! And just FYI, there's more strict goodies than just null checks! Setting `strict` to `true` enables them all, giving you lots of nice insults from the compiler whenever you forget something

**Comment by apotdevin** [comment]
Ah did not know about this `strict`... but more insults than `strictNullChecks`? 😔😂

Will enable it and check it out

**Comment by apotdevin** [comment]
![image](https://user-images.githubusercontent.com/31413433/87830279-02b56480-c881-11ea-9611-c66b6c9d73c5.png)

🙃

**Comment by apotdevin** [comment]
Created a PR for this, feel free to grab any flag!
