### ISSUE TITLE
Need a Loading Animation on channel close dialog

### ISSUE THREAD

**Issue by Jestopher-BTC** [apotdevin/thunderhub#99]
**Is your feature request related to a problem? Please describe.**
When I go to close a channel, I click Close channel. Then I get an additional popup that asks me if I want to close the channel. When I click to close the channel, there's no visual change that the command was accepted for several seconds. I'm pressured to click the close channel button again without any visual feedback.

**Describe the solution you'd like**
Show a processing animation or a loading bar when the close channel process starts.

**Describe alternatives you've considered**
It would be nice to optionally see the command as it is processing in a verbose mode for detailed troubleshooting.

**Comment by apotdevin** [comment]
Just checked and there is a loading animation when you close a channel.

I did some refactoring just in case but it's odd that this happens to you.

Will close this, let me know if it happens to you again!
